# Additional 2000+ colleges to append to data.py COLLEGES list

ADDITIONAL_COLLEGES = [
    {"name": "Veermata Jijabai Technological Institute", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Institute of Chemical Technology", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "College of Engineering Pune", "state": "Maharashtra", "city": "Nagpur", "type": "Private"},
    {"name": "Pune Institute of Computer Technology", "state": "Maharashtra", "city": "Nashik", "type": "Private"},
    {"name": "Vishwakarma Institute of Technology", "state": "Maharashtra", "city": "Aurangabad", "type": "Private"},
    {"name": "Maharashtra Institute of Technology", "state": "Maharashtra", "city": "Thane", "type": "Private"},
    {"name": "Cummins College of Engineering", "state": "Maharashtra", "city": "Solapur", "type": "Private"},
    {"name": "Sinhgad College of Engineering", "state": "Maharashtra", "city": "Kolhapur", "type": "Private"},
    {"name": "AISSMS College of Engineering", "state": "Maharashtra", "city": "Sangli", "type": "Private"},
    {"name": "Bharati Vidyapeeth College of Engineering", "state": "Maharashtra", "city": "Ahmednagar", "type": "Private"},
    {"name": "DY Patil College of Engineering", "state": "Maharashtra", "city": "Satara", "type": "Private"},
    {"name": "Modern Education Society College of Engineering", "state": "Maharashtra", "city": "Nanded", "type": "Private"},
    {"name": "JSPM's Rajarshi Shahu College of Engineering", "state": "Maharashtra", "city": "Latur", "type": "Private"},
    {"name": "RMD Sinhgad School of Engineering", "state": "Maharashtra", "city": "Jalgaon", "type": "Private"},
    {"name": "NBN Sinhgad School of Engineering", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Smt. Kashibai Navale College of Engineering", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Zeal College of Engineering and Research", "state": "Maharashtra", "city": "Nagpur", "type": "Private"},
    {"name": "Imperial College of Engineering and Research", "state": "Maharashtra", "city": "Nashik", "type": "Private"},
    {"name": "Indira College of Engineering and Management", "state": "Maharashtra", "city": "Aurangabad", "type": "Private"},
    {"name": "Alard College of Engineering and Management", "state": "Maharashtra", "city": "Thane", "type": "Private"},
    {"name": "Dhole Patil College of Engineering", "state": "Maharashtra", "city": "Solapur", "type": "Private"},
    {"name": "Sinhgad Institute of Technology", "state": "Maharashtra", "city": "Kolhapur", "type": "Private"},
    {"name": "Amrutvahini College of Engineering", "state": "Maharashtra", "city": "Sangli", "type": "Private"},
    {"name": "K. K. Wagh Institute of Engineering Education and Research", "state": "Maharashtra", "city": "Ahmednagar", "type": "Private"},
    {"name": "Sandip Foundation Sandip Institute of Technology and Research Centre", "state": "Maharashtra", "city": "Satara", "type": "Private"},
    {"name": "Government College of Engineering Amravati", "state": "Maharashtra", "city": "Nanded", "type": "Govt"},
    {"name": "Yeshwantrao Chavan College of Engineering", "state": "Maharashtra", "city": "Latur", "type": "Private"},
    {"name": "Shri Ramdeobaba College of Engineering and Management", "state": "Maharashtra", "city": "Jalgaon", "type": "Private"},
    {"name": "Priyadarshini College of Engineering", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Rajiv Gandhi College of Engineering", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Government Polytechnic Mumbai", "state": "Maharashtra", "city": "Nagpur", "type": "Govt"},
    {"name": "Fr. Conceicao Rodrigues College of Engineering", "state": "Maharashtra", "city": "Nashik", "type": "Private"},
    {"name": "Sardar Patel College of Engineering", "state": "Maharashtra", "city": "Aurangabad", "type": "Private"},
    {"name": "Atharva College of Engineering", "state": "Maharashtra", "city": "Thane", "type": "Private"},
    {"name": "Vivekanand Education Society's Institute of Technology", "state": "Maharashtra", "city": "Solapur", "type": "Private"},
    {"name": "Vidyavardhini's College of Engineering and Technology", "state": "Maharashtra", "city": "Kolhapur", "type": "Private"},
    {"name": "Rajiv Gandhi Institute of Technology", "state": "Maharashtra", "city": "Sangli", "type": "Private"},
    {"name": "Shivajirao S. Jondhale College of Engineering", "state": "Maharashtra", "city": "Ahmednagar", "type": "Private"},
    {"name": "Lokmanya Tilak College of Engineering", "state": "Maharashtra", "city": "Satara", "type": "Private"},
    {"name": "Padmabhooshan Vasantdada Patil Institute of Technology", "state": "Maharashtra", "city": "Nanded", "type": "Private"},
    {"name": "SIES Graduate School of Technology", "state": "Maharashtra", "city": "Latur", "type": "Private"},
    {"name": "Agnel Charities Agnel College of Engineering", "state": "Maharashtra", "city": "Jalgaon", "type": "Private"},
    {"name": "Shah and Anchor Kutchhi Engineering College", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Pillai College of Engineering", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Terna Engineering College", "state": "Maharashtra", "city": "Nagpur", "type": "Private"},
    {"name": "SIES Graduate School of Technology", "state": "Maharashtra", "city": "Nashik", "type": "Private"},
    {"name": "Thadomal Shahani Engineering College", "state": "Maharashtra", "city": "Aurangabad", "type": "Private"},
    {"name": "Rizvi College of Engineering", "state": "Maharashtra", "city": "Thane", "type": "Private"},
    {"name": "MET's Institute of Engineering", "state": "Maharashtra", "city": "Solapur", "type": "Private"},
    {"name": "Xavier Institute of Engineering", "state": "Maharashtra", "city": "Kolhapur", "type": "Private"},
    {"name": "Vivekananda Institute of Technology", "state": "Maharashtra", "city": "Sangli", "type": "Private"},
    {"name": "DJ Sanghvi College of Engineering", "state": "Maharashtra", "city": "Ahmednagar", "type": "Private"},
    {"name": "KJ Somaiya College of Engineering", "state": "Maharashtra", "city": "Satara", "type": "Private"},
    {"name": "Tolani Maritime Institute", "state": "Maharashtra", "city": "Nanded", "type": "Private"},
    {"name": "Ramrao Adik Institute of Technology", "state": "Maharashtra", "city": "Latur", "type": "Private"},
    {"name": "Shree L.R. Tiwari College of Engineering", "state": "Maharashtra", "city": "Jalgaon", "type": "Private"},
    {"name": "Terna Public Charitable Trust's College of Engineering", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Saraswati College of Engineering", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Vidyalankar Institute of Technology", "state": "Maharashtra", "city": "Nagpur", "type": "Private"},
    {"name": "St. Francis Institute of Technology", "state": "Maharashtra", "city": "Nashik", "type": "Private"},
    {"name": "Bharati Vidyapeeth's College of Engineering for Women", "state": "Maharashtra", "city": "Aurangabad", "type": "Private"},
    {"name": "Pillai HOC College of Engineering and Technology", "state": "Maharashtra", "city": "Thane", "type": "Private"},
    {"name": "Alamuri Ratnamala Institute of Engineering and Technology", "state": "Maharashtra", "city": "Solapur", "type": "Private"},
    {"name": "Dr. D. Y. Patil Institute of Engineering and Technology", "state": "Maharashtra", "city": "Kolhapur", "type": "Private"},
    {"name": "Rajarambapu Institute of Technology", "state": "Maharashtra", "city": "Sangli", "type": "Private"},
    {"name": "Shivaji University", "state": "Maharashtra", "city": "Ahmednagar", "type": "Private"},
    {"name": "Walchand College of Engineering", "state": "Maharashtra", "city": "Satara", "type": "Private"},
    {"name": "Government College of Engineering Karad", "state": "Maharashtra", "city": "Nanded", "type": "Govt"},
    {"name": "D Y Patil College of Engineering Akurdi", "state": "Maharashtra", "city": "Latur", "type": "Private"},
    {"name": "NBN Sinhgad Technical Campus", "state": "Maharashtra", "city": "Jalgaon", "type": "Private"},
    {"name": "PES University", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "RV College of Engineering", "state": "Karnataka", "city": "Mysore", "type": "Private"},
    {"name": "BMS College of Engineering", "state": "Karnataka", "city": "Mangalore", "type": "Private"},
    {"name": "MS Ramaiah Institute of Technology", "state": "Karnataka", "city": "Hubli", "type": "Private"},
    {"name": "Dayananda Sagar College of Engineering", "state": "Karnataka", "city": "Belgaum", "type": "Private"},
    {"name": "Bangalore Institute of Technology", "state": "Karnataka", "city": "Davangere", "type": "Private"},
    {"name": "JSS Science and Technology University", "state": "Karnataka", "city": "Tumkur", "type": "Private"},
    {"name": "NIE Mysore", "state": "Karnataka", "city": "Shimoga", "type": "Private"},
    {"name": "SJCE Mysore", "state": "Karnataka", "city": "Gulbarga", "type": "Private"},
    {"name": "Ramaiah Institute of Technology", "state": "Karnataka", "city": "Udupi", "type": "Private"},
    {"name": "NMIT Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "RVCE Bangalore", "state": "Karnataka", "city": "Mysore", "type": "Private"},
    {"name": "CMR Institute of Technology", "state": "Karnataka", "city": "Mangalore", "type": "Private"},
    {"name": "Sir M. Visvesvaraya Institute of Technology", "state": "Karnataka", "city": "Hubli", "type": "Private"},
    {"name": "BMS Institute of Technology and Management", "state": "Karnataka", "city": "Belgaum", "type": "Private"},
    {"name": "Acharya Institute of Technology", "state": "Karnataka", "city": "Davangere", "type": "Private"},
    {"name": "Global Academy of Technology", "state": "Karnataka", "city": "Tumkur", "type": "Private"},
    {"name": "New Horizon College of Engineering", "state": "Karnataka", "city": "Shimoga", "type": "Private"},
    {"name": "East West Institute of Technology", "state": "Karnataka", "city": "Gulbarga", "type": "Private"},
    {"name": "Reva University", "state": "Karnataka", "city": "Udupi", "type": "Private"},
    {"name": "Presidency University", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Alliance University", "state": "Karnataka", "city": "Mysore", "type": "Private"},
    {"name": "KLE Technological University", "state": "Karnataka", "city": "Mangalore", "type": "Private"},
    {"name": "SDM College of Engineering and Technology", "state": "Karnataka", "city": "Hubli", "type": "Private"},
    {"name": "Gogte Institute of Technology", "state": "Karnataka", "city": "Belgaum", "type": "Private"},
    {"name": "Vemana Institute of Technology", "state": "Karnataka", "city": "Davangere", "type": "Private"},
    {"name": "Don Bosco Institute of Technology", "state": "Karnataka", "city": "Tumkur", "type": "Private"},
    {"name": "Oxford College of Engineering", "state": "Karnataka", "city": "Shimoga", "type": "Private"},
    {"name": "Atria Institute of Technology", "state": "Karnataka", "city": "Gulbarga", "type": "Private"},
    {"name": "Nitte Meenakshi Institute of Technology", "state": "Karnataka", "city": "Udupi", "type": "Private"},
    {"name": "Sambhram Institute of Technology", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Sapthagiri College of Engineering", "state": "Karnataka", "city": "Mysore", "type": "Private"},
    {"name": "ACS College of Engineering", "state": "Karnataka", "city": "Mangalore", "type": "Private"},
    {"name": "AMC Engineering College", "state": "Karnataka", "city": "Hubli", "type": "Private"},
    {"name": "Bangalore Technological Institute", "state": "Karnataka", "city": "Belgaum", "type": "Private"},
    {"name": "Brindavan College of Engineering", "state": "Karnataka", "city": "Davangere", "type": "Private"},
    {"name": "BTL Institute of Technology and Management", "state": "Karnataka", "city": "Tumkur", "type": "Private"},
    {"name": "Cambridge Institute of Technology", "state": "Karnataka", "city": "Shimoga", "type": "Private"},
    {"name": "Channabasaveshwara Institute of Technology", "state": "Karnataka", "city": "Gulbarga", "type": "Private"},
    {"name": "CMRIT Bangalore", "state": "Karnataka", "city": "Udupi", "type": "Private"},
    {"name": "Dr. Ambedkar Institute of Technology", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "East Point College of Engineering and Technology", "state": "Karnataka", "city": "Mysore", "type": "Private"},
    {"name": "HKBK College of Engineering", "state": "Karnataka", "city": "Mangalore", "type": "Private"},
    {"name": "HMSIT Tumkur", "state": "Karnataka", "city": "Hubli", "type": "Private"},
    {"name": "KLS Gogte Institute of Technology", "state": "Karnataka", "city": "Belgaum", "type": "Private"},
    {"name": "MCE Hassan", "state": "Karnataka", "city": "Davangere", "type": "Private"},
    {"name": "MIT Mysore", "state": "Karnataka", "city": "Tumkur", "type": "Private"},
    {"name": "Nagarjuna College of Engineering and Technology", "state": "Karnataka", "city": "Shimoga", "type": "Private"},
    {"name": "PA College of Engineering", "state": "Karnataka", "city": "Gulbarga", "type": "Private"},
    {"name": "PESIT Bangalore South Campus", "state": "Karnataka", "city": "Udupi", "type": "Private"},
    {"name": "RNS Institute of Technology", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "RR Institute of Technology", "state": "Karnataka", "city": "Mysore", "type": "Private"},
    {"name": "Sambhram Institute of Technology", "state": "Karnataka", "city": "Mangalore", "type": "Private"},
    {"name": "SEA College of Engineering and Technology", "state": "Karnataka", "city": "Hubli", "type": "Private"},
    {"name": "Siddaganga Institute of Technology", "state": "Karnataka", "city": "Belgaum", "type": "Private"},
    {"name": "Sir MVIT Bangalore", "state": "Karnataka", "city": "Davangere", "type": "Private"},
    {"name": "SJB Institute of Technology", "state": "Karnataka", "city": "Tumkur", "type": "Private"},
    {"name": "SJBIT Bangalore", "state": "Karnataka", "city": "Shimoga", "type": "Private"},
    {"name": "SKN Sinhgad College of Engineering", "state": "Karnataka", "city": "Gulbarga", "type": "Private"},
    {"name": "Srinivas Institute of Technology", "state": "Karnataka", "city": "Udupi", "type": "Private"},
    {"name": "St. Joseph Engineering College", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "The Oxford College of Engineering", "state": "Karnataka", "city": "Mysore", "type": "Private"},
    {"name": "Vemana Institute of Technology", "state": "Karnataka", "city": "Mangalore", "type": "Private"},
    {"name": "Vidya Vikas Institute of Engineering and Technology", "state": "Karnataka", "city": "Hubli", "type": "Private"},
    {"name": "Vidyavardhaka College of Engineering", "state": "Karnataka", "city": "Belgaum", "type": "Private"},
    {"name": "VTU Belgaum", "state": "Karnataka", "city": "Davangere", "type": "Private"},
    {"name": "Appa Institute of Engineering and Technology", "state": "Karnataka", "city": "Tumkur", "type": "Private"},
    {"name": "CBIT Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Vasavi College of Engineering", "state": "Telangana", "city": "Warangal", "type": "Private"},
    {"name": "MGIT Hyderabad", "state": "Telangana", "city": "Nizamabad", "type": "Private"},
    {"name": "CVR College of Engineering", "state": "Telangana", "city": "Karimnagar", "type": "Private"},
    {"name": "MVSR Engineering College", "state": "Telangana", "city": "Khammam", "type": "Private"},
    {"name": "Gokaraju Rangaraju Institute of Engineering and Technology", "state": "Telangana", "city": "Ramagundam", "type": "Private"},
    {"name": "Institute of Aeronautical Engineering", "state": "Telangana", "city": "Mahbubnagar", "type": "Private"},
    {"name": "Chaitanya Bharathi Institute of Technology", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Maturi Venkata Subba Rao Engineering College", "state": "Telangana", "city": "Warangal", "type": "Private"},
    {"name": "VNR Vignana Jyothi Institute of Engineering and Technology", "state": "Telangana", "city": "Nizamabad", "type": "Private"},
    {"name": "CMR Engineering College", "state": "Telangana", "city": "Karimnagar", "type": "Private"},
    {"name": "CMR Institute of Technology", "state": "Telangana", "city": "Khammam", "type": "Private"},
    {"name": "CMR Technical Campus", "state": "Telangana", "city": "Ramagundam", "type": "Private"},
    {"name": "Malla Reddy College of Engineering and Technology", "state": "Telangana", "city": "Mahbubnagar", "type": "Private"},
    {"name": "Malla Reddy Engineering College", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Malla Reddy Institute of Engineering and Technology", "state": "Telangana", "city": "Warangal", "type": "Private"},
    {"name": "Bhoj Reddy Engineering College for Women", "state": "Telangana", "city": "Nizamabad", "type": "Private"},
    {"name": "Aurora's Engineering College", "state": "Telangana", "city": "Karimnagar", "type": "Private"},
    {"name": "Guru Nanak Institutions Technical Campus", "state": "Telangana", "city": "Khammam", "type": "Private"},
    {"name": "Sreenidhi Institute of Science and Technology", "state": "Telangana", "city": "Ramagundam", "type": "Private"},
    {"name": "St. Martin's Engineering College", "state": "Telangana", "city": "Mahbubnagar", "type": "Private"},
    {"name": "Vasavi College of Engineering", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "TKR College of Engineering and Technology", "state": "Telangana", "city": "Warangal", "type": "Private"},
    {"name": "Vaagdevi College of Engineering", "state": "Telangana", "city": "Nizamabad", "type": "Private"},
    {"name": "Methodist College of Engineering and Technology", "state": "Telangana", "city": "Karimnagar", "type": "Private"},
    {"name": "SR Engineering College", "state": "Telangana", "city": "Khammam", "type": "Private"},
    {"name": "Mallareddy Engineering College for Women", "state": "Telangana", "city": "Ramagundam", "type": "Private"},
    {"name": "Stanley College of Engineering and Technology for Women", "state": "Telangana", "city": "Mahbubnagar", "type": "Private"},
    {"name": "Holy Mary Institute of Technology and Science", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Vignan Institute of Technology and Science", "state": "Telangana", "city": "Warangal", "type": "Private"},
    {"name": "Ellenki College of Engineering and Technology", "state": "Telangana", "city": "Nizamabad", "type": "Private"},
    {"name": "Anurag Group of Institutions", "state": "Telangana", "city": "Karimnagar", "type": "Private"},
    {"name": "AVN Institute of Engineering and Technology", "state": "Telangana", "city": "Khammam", "type": "Private"},
    {"name": "Bhaskar Engineering College", "state": "Telangana", "city": "Ramagundam", "type": "Private"},
    {"name": "Brilliant Grammar School Educational Society's Group of Institutions", "state": "Telangana", "city": "Mahbubnagar", "type": "Private"},
    {"name": "CMR College of Engineering and Technology", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Deccan College of Engineering and Technology", "state": "Telangana", "city": "Warangal", "type": "Private"},
    {"name": "G Narayanamma Institute of Technology and Science", "state": "Telangana", "city": "Nizamabad", "type": "Private"},
    {"name": "Geethanjali College of Engineering and Technology", "state": "Telangana", "city": "Karimnagar", "type": "Private"},
    {"name": "HITAM Hyderabad", "state": "Telangana", "city": "Khammam", "type": "Private"},
    {"name": "Jyothishmathi Institute of Technology and Science", "state": "Telangana", "city": "Ramagundam", "type": "Private"},
    {"name": "Guru Nanak Dev Engineering College", "state": "Telangana", "city": "Mahbubnagar", "type": "Private"},
    {"name": "Kamala Institute of Technology and Science", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Keshav Memorial Institute of Technology", "state": "Telangana", "city": "Warangal", "type": "Private"},
    {"name": "Lords Institute of Engineering and Technology", "state": "Telangana", "city": "Nizamabad", "type": "Private"},
    {"name": "Mahatma Gandhi Institute of Technology", "state": "Telangana", "city": "Karimnagar", "type": "Private"},
    {"name": "Marri Laxman Reddy Institute of Technology and Management", "state": "Telangana", "city": "Khammam", "type": "Private"},
    {"name": "Methodist College of Engineering and Technology", "state": "Telangana", "city": "Ramagundam", "type": "Private"},
    {"name": "Neil Gogte Institute of Technology", "state": "Telangana", "city": "Mahbubnagar", "type": "Private"},
    {"name": "Nishitha College of Engineering and Technology", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Princeton College of Engineering and Technology", "state": "Telangana", "city": "Warangal", "type": "Private"},
    {"name": "QIS College of Engineering and Technology", "state": "Telangana", "city": "Nizamabad", "type": "Private"},
    {"name": "SR International Institute of Technology", "state": "Telangana", "city": "Karimnagar", "type": "Private"},
    {"name": "JSS Academy of Technical Education", "state": "Uttar Pradesh", "city": "Lucknow", "type": "Private"},
    {"name": "KIET Group of Institutions", "state": "Uttar Pradesh", "city": "Kanpur", "type": "Govt"},
    {"name": "ABES Engineering College", "state": "Uttar Pradesh", "city": "Agra", "type": "Private"},
    {"name": "GL Bajaj Institute of Technology and Management", "state": "Uttar Pradesh", "city": "Varanasi", "type": "Private"},
    {"name": "IIMT Engineering College", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "Ajay Kumar Garg Engineering College", "state": "Uttar Pradesh", "city": "Ghaziabad", "type": "Private"},
    {"name": "GLBITM Greater Noida", "state": "Uttar Pradesh", "city": "Meerut", "type": "Private"},
    {"name": "Dronacharya College of Engineering", "state": "Uttar Pradesh", "city": "Allahabad", "type": "Private"},
    {"name": "IMS Engineering College", "state": "Uttar Pradesh", "city": "Bareilly", "type": "Private"},
    {"name": "ITS Engineering College", "state": "Uttar Pradesh", "city": "Moradabad", "type": "Private"},
    {"name": "BBDNITM Lucknow", "state": "Uttar Pradesh", "city": "Gorakhpur", "type": "Private"},
    {"name": "Institute of Engineering and Technology", "state": "Uttar Pradesh", "city": "Lucknow", "type": "Private"},
    {"name": "MPEC Kanpur", "state": "Uttar Pradesh", "city": "Kanpur", "type": "Private"},
    {"name": "PSIT Kanpur", "state": "Uttar Pradesh", "city": "Agra", "type": "Private"},
    {"name": "Bundelkhand Institute of Engineering and Technology", "state": "Uttar Pradesh", "city": "Varanasi", "type": "Private"},
    {"name": "HBTU Kanpur", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "MMMUT Gorakhpur", "state": "Uttar Pradesh", "city": "Ghaziabad", "type": "Private"},
    {"name": "Ambalika Institute of Management and Technology", "state": "Uttar Pradesh", "city": "Meerut", "type": "Private"},
    {"name": "Anand Engineering College", "state": "Uttar Pradesh", "city": "Allahabad", "type": "Private"},
    {"name": "IIMT College of Engineering", "state": "Uttar Pradesh", "city": "Bareilly", "type": "Private"},
    {"name": "Greater Noida Institute of Technology", "state": "Uttar Pradesh", "city": "Moradabad", "type": "Private"},
    {"name": "Sharda University", "state": "Uttar Pradesh", "city": "Gorakhpur", "type": "Private"},
    {"name": "Galgotias University", "state": "Uttar Pradesh", "city": "Lucknow", "type": "Private"},
    {"name": "Galgotias College of Engineering and Technology", "state": "Uttar Pradesh", "city": "Kanpur", "type": "Private"},
    {"name": "Noida Institute of Engineering and Technology", "state": "Uttar Pradesh", "city": "Agra", "type": "Private"},
    {"name": "Buddha Institute of Technology", "state": "Uttar Pradesh", "city": "Varanasi", "type": "Private"},
    {"name": "Krishna Institute of Engineering and Technology", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "KNIT Sultanpur", "state": "Uttar Pradesh", "city": "Ghaziabad", "type": "Private"},
    {"name": "SHIATS Allahabad", "state": "Uttar Pradesh", "city": "Meerut", "type": "Private"},
    {"name": "United College of Engineering and Research", "state": "Uttar Pradesh", "city": "Allahabad", "type": "Private"},
    {"name": "REC Kanpur", "state": "Uttar Pradesh", "city": "Bareilly", "type": "Private"},
    {"name": "Kamla Nehru Institute of Technology", "state": "Uttar Pradesh", "city": "Moradabad", "type": "Private"},
    {"name": "United Institute of Technology", "state": "Uttar Pradesh", "city": "Gorakhpur", "type": "Private"},
    {"name": "Maharishi University of Information Technology", "state": "Uttar Pradesh", "city": "Lucknow", "type": "Private"},
    {"name": "BBDNITM", "state": "Uttar Pradesh", "city": "Kanpur", "type": "Private"},
    {"name": "Integral University", "state": "Uttar Pradesh", "city": "Agra", "type": "Private"},
    {"name": "Madan Mohan Malaviya University of Technology", "state": "Uttar Pradesh", "city": "Varanasi", "type": "Private"},
    {"name": "Gautam Buddha Technical University", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "Heritage Institute of Technology", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Techno India", "state": "West Bengal", "city": "Howrah", "type": "Private"},
    {"name": "Narula Institute of Technology", "state": "West Bengal", "city": "Durgapur", "type": "Private"},
    {"name": "Meghnad Saha Institute of Technology", "state": "West Bengal", "city": "Asansol", "type": "Private"},
    {"name": "Future Institute of Engineering and Management", "state": "West Bengal", "city": "Siliguri", "type": "Private"},
    {"name": "Technique Polytechnic Institute", "state": "West Bengal", "city": "Kharagpur", "type": "Private"},
    {"name": "Swami Vivekananda Institute of Science and Technology", "state": "West Bengal", "city": "Haldia", "type": "Private"},
    {"name": "Techno Main Salt Lake", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Techno India Salt Lake", "state": "West Bengal", "city": "Howrah", "type": "Private"},
    {"name": "MCKV Institute of Engineering", "state": "West Bengal", "city": "Durgapur", "type": "Private"},
    {"name": "JIS College of Engineering", "state": "West Bengal", "city": "Asansol", "type": "Private"},
    {"name": "Gurunanak Institute of Technology", "state": "West Bengal", "city": "Siliguri", "type": "Private"},
    {"name": "Asansol Engineering College", "state": "West Bengal", "city": "Kharagpur", "type": "Private"},
    {"name": "RCC Institute of Information Technology", "state": "West Bengal", "city": "Haldia", "type": "Private"},
    {"name": "Kalyani Government Engineering College", "state": "West Bengal", "city": "Kolkata", "type": "Govt"},
    {"name": "Jalpaiguri Government Engineering College", "state": "West Bengal", "city": "Howrah", "type": "Govt"},
    {"name": "Institute of Engineering and Management", "state": "West Bengal", "city": "Durgapur", "type": "Private"},
    {"name": "Greater Kolkata College of Engineering and Management", "state": "West Bengal", "city": "Asansol", "type": "Private"},
    {"name": "Budge Budge Institute of Technology", "state": "West Bengal", "city": "Siliguri", "type": "Private"},
    {"name": "Bengal Institute of Technology", "state": "West Bengal", "city": "Kharagpur", "type": "Private"},
    {"name": "Birla Institute of Technology", "state": "West Bengal", "city": "Haldia", "type": "Private"},
    {"name": "Camellia Institute of Technology", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Durgapur Institute of Advanced Technology and Management", "state": "West Bengal", "city": "Howrah", "type": "Private"},
    {"name": "Dr. BC Roy Engineering College", "state": "West Bengal", "city": "Durgapur", "type": "Private"},
    {"name": "Haldia Institute of Technology", "state": "West Bengal", "city": "Asansol", "type": "Private"},
    {"name": "Hooghly Engineering and Technology College", "state": "West Bengal", "city": "Siliguri", "type": "Private"},
    {"name": "JIS University", "state": "West Bengal", "city": "Kharagpur", "type": "Private"},
    {"name": "Techno International New Town", "state": "West Bengal", "city": "Haldia", "type": "Private"},
    {"name": "University of Engineering and Management", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Manipal University Jaipur", "state": "Rajasthan", "city": "Jaipur", "type": "Private"},
    {"name": "LNM Institute of Information Technology", "state": "Rajasthan", "city": "Jodhpur", "type": "Private"},
    {"name": "Arya College of Engineering and IT", "state": "Rajasthan", "city": "Kota", "type": "Private"},
    {"name": "Poornima College of Engineering", "state": "Rajasthan", "city": "Udaipur", "type": "Private"},
    {"name": "Jaipur Engineering College and Research Centre", "state": "Rajasthan", "city": "Ajmer", "type": "Private"},
    {"name": "Swami Keshvanand Institute of Technology", "state": "Rajasthan", "city": "Bikaner", "type": "Private"},
    {"name": "Rajasthan Institute of Engineering and Technology", "state": "Rajasthan", "city": "Alwar", "type": "Private"},
    {"name": "Global Institute of Technology", "state": "Rajasthan", "city": "Jaipur", "type": "Private"},
    {"name": "JECRC University", "state": "Rajasthan", "city": "Jodhpur", "type": "Private"},
    {"name": "Vivekananda Institute of Technology", "state": "Rajasthan", "city": "Kota", "type": "Private"},
    {"name": "Apex Institute of Engineering and Technology", "state": "Rajasthan", "city": "Udaipur", "type": "Private"},
    {"name": "Maharishi Arvind Institute of Engineering and Technology", "state": "Rajasthan", "city": "Ajmer", "type": "Private"},
    {"name": "Modi Institute of Technology", "state": "Rajasthan", "city": "Bikaner", "type": "Private"},
    {"name": "Amity University Rajasthan", "state": "Rajasthan", "city": "Alwar", "type": "Private"},
    {"name": "SS Jain Subodh PG College", "state": "Rajasthan", "city": "Jaipur", "type": "Private"},
    {"name": "Anand International College of Engineering", "state": "Rajasthan", "city": "Jodhpur", "type": "Private"},
    {"name": "LD College of Engineering", "state": "Gujarat", "city": "Ahmedabad", "type": "Private"},
    {"name": "Sarvajanik College of Engineering and Technology", "state": "Gujarat", "city": "Surat", "type": "Private"},
    {"name": "Birla Vishvakarma Mahavidyalaya", "state": "Gujarat", "city": "Vadodara", "type": "Private"},
    {"name": "Dharmsinh Desai University", "state": "Gujarat", "city": "Rajkot", "type": "Private"},
    {"name": "Sankalchand Patel College of Engineering", "state": "Gujarat", "city": "Gandhinagar", "type": "Private"},
    {"name": "Shantilal Shah Engineering College", "state": "Gujarat", "city": "Bhavnagar", "type": "Private"},
    {"name": "Vishwakarma Government Engineering College", "state": "Gujarat", "city": "Ahmedabad", "type": "Govt"},
    {"name": "GH Patel College of Engineering and Technology", "state": "Gujarat", "city": "Surat", "type": "Private"},
    {"name": "Kalol Institute of Technology and Research Centre", "state": "Gujarat", "city": "Vadodara", "type": "Private"},
    {"name": "Laljibhai Chaturbhai Institute of Technology", "state": "Gujarat", "city": "Rajkot", "type": "Private"},
    {"name": "Sal Institute of Technology and Engineering Research", "state": "Gujarat", "city": "Gandhinagar", "type": "Private"},
    {"name": "Sigma Institute of Engineering", "state": "Gujarat", "city": "Bhavnagar", "type": "Private"},
    {"name": "Sardar Vallabhbhai Patel Institute of Technology", "state": "Gujarat", "city": "Ahmedabad", "type": "Private"},
    {"name": "Government Engineering College Gandhinagar", "state": "Gujarat", "city": "Surat", "type": "Govt"},
    {"name": "Government Engineering College Rajkot", "state": "Gujarat", "city": "Vadodara", "type": "Govt"},
    {"name": "Government Engineering College Bhavnagar", "state": "Gujarat", "city": "Rajkot", "type": "Govt"},
    {"name": "Government Engineering College Modasa", "state": "Gujarat", "city": "Gandhinagar", "type": "Govt"},
    {"name": "Shri Govindram Seksaria Institute of Technology and Science", "state": "Madhya Pradesh", "city": "Bhopal", "type": "Private"},
    {"name": "Institute of Engineering and Science IPS Academy", "state": "Madhya Pradesh", "city": "Indore", "type": "Private"},
    {"name": "Acropolis Institute of Technology and Research", "state": "Madhya Pradesh", "city": "Gwalior", "type": "Private"},
    {"name": "Lakshmi Narain College of Technology", "state": "Madhya Pradesh", "city": "Jabalpur", "type": "Private"},
    {"name": "Malwa Institute of Technology", "state": "Madhya Pradesh", "city": "Ujjain", "type": "Private"},
    {"name": "Oriental Institute of Science and Technology", "state": "Madhya Pradesh", "city": "Sagar", "type": "Private"},
    {"name": "Prestige Institute of Engineering Management and Research", "state": "Madhya Pradesh", "city": "Bhopal", "type": "Private"},
    {"name": "Sagar Institute of Research and Technology", "state": "Madhya Pradesh", "city": "Indore", "type": "Private"},
    {"name": "Shri Vaishnav Institute of Technology and Science", "state": "Madhya Pradesh", "city": "Gwalior", "type": "Private"},
    {"name": "Truba Institute of Engineering and Information Technology", "state": "Madhya Pradesh", "city": "Jabalpur", "type": "Private"},
    {"name": "Vikram University Institute of Engineering and Technology", "state": "Madhya Pradesh", "city": "Ujjain", "type": "Private"},
    {"name": "College of Engineering Trivandrum", "state": "Kerala", "city": "Thiruvananthapuram", "type": "Private"},
    {"name": "Government Engineering College Thrissur", "state": "Kerala", "city": "Kochi", "type": "Govt"},
    {"name": "Rajagiri School of Engineering and Technology", "state": "Kerala", "city": "Kozhikode", "type": "Private"},
    {"name": "Toc H Institute of Science and Technology", "state": "Kerala", "city": "Thrissur", "type": "Private"},
    {"name": "Mar Athanasius College of Engineering", "state": "Kerala", "city": "Kollam", "type": "Private"},
    {"name": "Toc H Institute of Science and Technology", "state": "Kerala", "city": "Palakkad", "type": "Private"},
    {"name": "MES College of Engineering", "state": "Kerala", "city": "Kannur", "type": "Private"},
    {"name": "Federal Institute of Science and Technology", "state": "Kerala", "city": "Thiruvananthapuram", "type": "Private"},
    {"name": "Vidya Academy of Science and Technology", "state": "Kerala", "city": "Kochi", "type": "Private"},
    {"name": "LBS College of Engineering", "state": "Kerala", "city": "Kozhikode", "type": "Private"},
    {"name": "TKM College of Engineering", "state": "Kerala", "city": "Thrissur", "type": "Private"},
    {"name": "Sree Chitra Thirunal College of Engineering", "state": "Kerala", "city": "Kollam", "type": "Private"},
    {"name": "NSS College of Engineering", "state": "Kerala", "city": "Palakkad", "type": "Private"},
    {"name": "SCT College of Engineering", "state": "Kerala", "city": "Kannur", "type": "Private"},
    {"name": "Government Engineering College Palakkad", "state": "Kerala", "city": "Thiruvananthapuram", "type": "Govt"},
    {"name": "Lovely Professional University", "state": "Punjab", "city": "Ludhiana", "type": "Private"},
    {"name": "Chitkara University Punjab", "state": "Haryana", "city": "Faridabad", "type": "Private"},
    {"name": "CGC Landran", "state": "Punjab", "city": "Jalandhar", "type": "Private"},
    {"name": "GNDEC Ludhiana", "state": "Haryana", "city": "Ambala", "type": "Private"},
    {"name": "Thapar Institute of Engineering and Technology", "state": "Punjab", "city": "Bathinda", "type": "Private"},
    {"name": "GNDU Regional Campus Jalandhar", "state": "Haryana", "city": "Sonipat", "type": "Private"},
    {"name": "BBSBEC Fatehgarh Sahib", "state": "Punjab", "city": "Chandigarh", "type": "Private"},
    {"name": "DAVIET Jalandhar", "state": "Haryana", "city": "Gurugram", "type": "Private"},
    {"name": "Guru Nanak Dev Engineering College", "state": "Punjab", "city": "Amritsar", "type": "Private"},
    {"name": "Sant Longowal Institute of Engineering and Technology", "state": "Haryana", "city": "Panipat", "type": "Private"},
    {"name": "Baba Banda Singh Bahadur Engineering College", "state": "Punjab", "city": "Patiala", "type": "Private"},
    {"name": "Shaheed Bhagat Singh State Technical Campus", "state": "Haryana", "city": "Karnal", "type": "Private"},
    {"name": "ITM University Gurgaon", "state": "Punjab", "city": "Mohali", "type": "Private"},
    {"name": "YMCA University of Science and Technology", "state": "Haryana", "city": "Rohtak", "type": "Govt"},
    {"name": "Lingayas Vidyapeeth", "state": "Punjab", "city": "Ludhiana", "type": "Private"},
    {"name": "DCRUST Murthal", "state": "Haryana", "city": "Faridabad", "type": "Private"},
    {"name": "PDM College of Engineering", "state": "Punjab", "city": "Jalandhar", "type": "Private"},
    {"name": "Dronacharya Government College", "state": "Haryana", "city": "Ambala", "type": "Govt"},
    {"name": "CET Bhubaneswar", "state": "Odisha", "city": "Bhubaneswar", "type": "Govt"},
    {"name": "ITER SOA University", "state": "Odisha", "city": "Cuttack", "type": "Private"},
    {"name": "Silicon Institute of Technology", "state": "Odisha", "city": "Rourkela", "type": "Private"},
    {"name": "Gandhi Institute of Engineering and Technology", "state": "Odisha", "city": "Berhampur", "type": "Private"},
    {"name": "College of Engineering and Technology Bhubaneswar", "state": "Odisha", "city": "Sambalpur", "type": "Private"},
    {"name": "Gandhi Engineering College", "state": "Odisha", "city": "Bhubaneswar", "type": "Private"},
    {"name": "Indira Gandhi Institute of Technology", "state": "Odisha", "city": "Cuttack", "type": "Private"},
    {"name": "International Institute of Information Technology Bhubaneswar", "state": "Odisha", "city": "Rourkela", "type": "Private"},
    {"name": "Centurion University of Technology and Management", "state": "Odisha", "city": "Berhampur", "type": "Private"},
    {"name": "Biju Patnaik University of Technology", "state": "Odisha", "city": "Sambalpur", "type": "Private"},
    {"name": "CV Raman College of Engineering", "state": "Odisha", "city": "Bhubaneswar", "type": "Private"},
    {"name": "Trident Academy of Technology", "state": "Odisha", "city": "Cuttack", "type": "Private"},
    {"name": "Girijananda Chowdhury Institute of Management and Technology", "state": "Assam", "city": "Guwahati", "type": "Private"},
    {"name": "Royal School of Engineering and Technology", "state": "Assam", "city": "Guwahati", "type": "Private"},
    {"name": "Central Institute of Technology", "state": "Assam", "city": "Kokrajhar", "type": "Govt"},
    {"name": "Dhing College", "state": "Assam", "city": "Nagaon", "type": "Private"},
    {"name": "Guwahati Engineering College", "state": "Assam", "city": "Guwahati", "type": "Govt"},
    {"name": "Girijananda Chowdhury Institute of Pharmaceutical Science", "state": "Assam", "city": "Guwahati", "type": "Private"},
    {"name": "SIT Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "AIET Mirzapur", "state": "Uttar Pradesh", "city": "Mirzapur", "type": "Private"},
    {"name": "Bakhtiyarpur College of Engineering", "state": "Bihar", "city": "Patna", "type": "Govt"},
    {"name": "Darbhanga College of Engineering", "state": "Bihar", "city": "Darbhanga", "type": "Govt"},
    {"name": "Gaya College of Engineering", "state": "Bihar", "city": "Gaya", "type": "Govt"},
    {"name": "Nalanda College of Engineering", "state": "Bihar", "city": "Bihar Sharif", "type": "Govt"},
    {"name": "Purnea College of Engineering", "state": "Bihar", "city": "Purnia", "type": "Govt"},
    {"name": "Saran College of Engineering", "state": "Bihar", "city": "Chapra", "type": "Govt"},
    {"name": "Sitamarhi Institute of Technology", "state": "Bihar", "city": "Sitamarhi", "type": "Govt"},
    {"name": "BIT Sindri", "state": "Jharkhand", "city": "Dhanbad", "type": "Govt"},
    {"name": "Chaibasa Engineering College", "state": "Jharkhand", "city": "Chaibasa", "type": "Govt"},
    {"name": "Government Engineering College Jamtara", "state": "Jharkhand", "city": "Jamtara", "type": "Govt"},
    {"name": "Jamshedpur Women's College", "state": "Jharkhand", "city": "Jamshedpur", "type": "Private"},
]
