# Indian Colleges Data

COLLEGES = [
    {"name": "Indian Institute of Technology Delhi", "state": "Delhi", "city": "New Delhi"},
    {"name": "Indian Institute of Technology Bombay", "state": "Maharashtra", "city": "Mumbai"},
    {"name": "Indian Institute of Technology Madras", "state": "Tamil Nadu", "city": "Chennai"},
    {"name": "Indian Institute of Technology Kanpur", "state": "Uttar Pradesh", "city": "Kanpur"},
    {"name": "Indian Institute of Technology Kharagpur", "state": "West Bengal", "city": "Kharagpur"},
    {"name": "Indian Institute of Science Bangalore", "state": "Karnataka", "city": "Bangalore"},
    {"name": "Jawaharlal Nehru University", "state": "Delhi", "city": "New Delhi"},
    {"name": "University of Delhi", "state": "Delhi", "city": "New Delhi"},
    {"name": "Anna University", "state": "Tamil Nadu", "city": "Chennai"},
    {"name": "Jadavpur University", "state": "West Bengal", "city": "Kolkata"},
    {"name": "Banaras Hindu University", "state": "Uttar Pradesh", "city": "Varanasi"},
    {"name": "Aligarh Muslim University", "state": "Uttar Pradesh", "city": "Aligarh"},
    {"name": "National Institute of Technology Trichy", "state": "Tamil Nadu", "city": "Tiruchirappalli"},
    {"name": "National Institute of Technology Warangal", "state": "Telangana", "city": "Warangal"},
    {"name": "Vellore Institute of Technology", "state": "Tamil Nadu", "city": "Vellore"},
    {"name": "Birla Institute of Technology and Science Pilani", "state": "Rajasthan", "city": "Pilani"},
    {"name": "Manipal Academy of Higher Education", "state": "Karnataka", "city": "Manipal"},
    {"name": "University of Hyderabad", "state": "Telangana", "city": "Hyderabad"},
    {"name": "Amity University Noida", "state": "Uttar Pradesh", "city": "Noida"},
    {"name": "SRM Institute of Science and Technology", "state": "Tamil Nadu", "city": "Chennai"},
    {"name": "Savitribai Phule Pune University", "state": "Maharashtra", "city": "Pune"},
    {"name": "Gujarat University", "state": "Gujarat", "city": "Ahmedabad"},
    {"name": "Osmania University", "state": "Telangana", "city": "Hyderabad"},
    {"name": "Calcutta University", "state": "West Bengal", "city": "Kolkata"},
    {"name": "Mumbai University", "state": "Maharashtra", "city": "Mumbai"},
    {"name": "Bangalore University", "state": "Karnataka", "city": "Bangalore"},
    {"name": "Panjab University", "state": "Punjab", "city": "Chandigarh"},
    {"name": "Lucknow University", "state": "Uttar Pradesh", "city": "Lucknow"},
    {"name": "Cochin University of Science and Technology", "state": "Kerala", "city": "Kochi"},
    {"name": "National Institute of Technology Karnataka", "state": "Karnataka", "city": "Surathkal"}
]
