# STUDENT MANAGEMENT SYSTEM - Central Data Repository
# This file contains all static data for states, cities, colleges, and departments

# ==================== STATES ====================
# Indian States and Union Territories

STATES = [
    # States (28)
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    # Union Territories (8)
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry"
]

# ==================== CITIES BY STATE ====================
# Comprehensive list of cities organized by state

CITIES_BY_STATE = {
    "Andhra Pradesh": [
        "Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Rajahmundry", "Tirupati",
        "Kadapa", "Anantapur", "Eluru", "Ongole", "Chittoor", "Machilipatnam", "Tenali", "Proddatur",
        "Vizianagaram", "Srikakulam", "Amadalavalasa", "Palasa", "Bobbili", "Narasannapeta",
        "Parvathipuram", "Ichchapuram", "Anakapalle", "Narsipatnam", "Pendurthi", "Yelamanchili",
        "Chodavaram", "Kakinada", "Amalapuram", "Mandapeta", "Ramachandrapuram", "Peddapuram",
        "Samalkot", "Tuni", "Razole", "Bhimavaram", "Tadepalligudem", "Narasapuram", "Tanuku",
        "Palakollu", "Nidadavole", "Jangareddygudem", "Gudivada", "Jaggaiahpet", "Nuzvid",
        "Mylavaram", "Avanigadda", "Kaikalur", "Mangalagiri", "Narasaraopet", "Chilakaluripet",
        "Piduguralla", "Sattenapalle", "Bapatla", "Repalle", "Ponnur", "Chirala", "Markapur",
        "Kandukur", "Addanki", "Giddalur", "Kavali", "Atmakur", "Gudur", "Venkatagiri", "Naidupet",
        "Sullurpeta", "Madanapalle", "Punganur", "Srikalahasti", "Nagari", "Palamaner", "Vayalpadu",
        "Pulivendula", "Jammalamadugu", "Mydukur", "Rayachoti", "Badvel", "Hindupur", "Dharmavaram",
        "Kadiri", "Guntakal", "Tadipatri", "Penukonda", "Kalyandurg", "Adoni", "Nandyal",
        "Yemmiganur", "Allagadda", "Banaganapalle", "Dhone", "Kodumur"
    ],
    "Arunachal Pradesh": [
        "Itanagar", "Naharlagun", "Nirjuli", "Banderdewa", "Pasighat", "Aalo", "Basar", "Likabali",
        "Ruksin", "Tawang", "Lumla", "Zemithang", "Jang", "Ziro", "Yachuli", "Daporijo", "Sagalee",
        "Kimin", "Tezu", "Wakro", "Changlang", "Jairampur", "Miao", "Khonsa", "Longding", "Roing",
        "Anini", "Seppa", "Bomdila", "Dirang", "Hawai", "Palin", "Koloriang", "Lemmi"
    ],
    "Assam": [
        "Guwahati", "Dibrugarh", "Silchar", "Jorhat", "Tezpur", "Nagaon", "Tinsukia", "Sivasagar",
        "Dhubri", "Goalpara", "Bongaigaon", "Karimganj", "Lakhimpur", "Morigaon", "Hojai",
        "Duliajan", "Digboi", "Margherita", "Nazira", "Sonari", "Moranhat", "Naharkatia",
        "Lanka", "Lumding", "Kampur", "Bokakhat", "Dergaon", "Barpeta", "Barpeta Road",
        "Abhayapuri", "Bijni", "Pathsala", "Rangia", "Gauripur", "Bilasipara", "Sapatgram",
        "Hailakandi", "Badarpur", "Lala", "Mangaldoi", "Udalguri", "Tangla", "Dhekiajuli",
        "Biswanath Chariali", "Diphu", "Bokajan", "Haflong", "Umrangso", "Kokrajhar",
        "Gossaigaon", "Chirang", "Golaghat", "Majuli", "Sarupathar", "Amguri", "Chapar", "Lakhipur"
    ],
    "Bihar": [
        "Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga", "Purnia", "Arrah", "Begusarai",
        "Bihar Sharif", "Katihar", "Munger", "Chapra", "Danapur", "Saharsa", "Sasaram", "Hajipur",
        "Dehri", "Siwan", "Motihari", "Nawada", "Bagaha", "Buxar", "Kishanganj", "Sitamarhi",
        "Jamalpur", "Jehanabad", "Aurangabad", "Lakhisarai", "Sheikhpura", "Bettiah", "Madhubani",
        "Samastipur", "Gopalganj", "Supaul", "Madhepura", "Khagaria", "Sheohar", "Araria"
    ],
    "Chhattisgarh": [
        "Raipur", "Bhilai", "Bilaspur", "Durg", "Korba", "Rajnandgaon", "Raigarh", "Jagdalpur",
        "Ambikapur", "Dhamtari", "Mahasamund", "Bhatapara", "Chirmiri", "Janjgir", "Sakti",
        "Dalli-Rajhara", "Tilda", "Manendragarh", "Champa", "Bemetara", "Patan", "Balod",
        "Simga", "Mungeli", "Dongargarh", "Baloda Bazar", "Kawardha"
    ],
    "Goa": [
        "Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda", "Bicholim", "Curchorem",
        "Sanquelim", "Cuncolim", "Quepem", "Canacona", "Valpoi", "Pernem", "Sanguem"
    ],
    "Gujarat": [
        "Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar", "Bhavnagar", "Jamnagar",
        "Junagadh", "Anand", "Nadiad", "Morbi", "Surendranagar", "Bharuch", "Mehsana",
        "Gandhidham", "Vapi", "Navsari", "Veraval", "Porbandar", "Godhra", "Botad",
        "Amreli", "Deesa", "Jetpur", "Gondal", "Palanpur", "Valsad", "Patan", "Bhuj",
        "Dahod", "Modasa", "Kalol", "Visnagar", "Mandvi", "Vyara", "Himmatnagar"
    ],
    "Haryana": [
        "Gurugram", "Faridabad", "Panipat", "Ambala", "Yamunanagar", "Rohtak", "Hisar",
        "Karnal", "Sonipat", "Panchkula", "Bhiwani", "Sirsa", "Bahadurgarh", "Jind",
        "Thanesar", "Kaithal", "Rewari", "Palwal", "Gohana", "Hansi", "Narnaul",
        "Fatehabad", "Tohana", "Charkhi Dadri", "Mahendragarh", "Narwana", "Pundri"
    ],
    "Himachal Pradesh": [
        "Shimla", "Solan", "Mandi", "Dharamshala", "Palampur", "Kullu", "Hamirpur", "Bilaspur",
        "Kangra", "Una", "Nahan", "Chamba", "Sundarnagar", "Paonta Sahib", "Baddi", "Nalagarh",
        "Parwanoo", "Kasauli", "Rampur", "Arki", "Manali", "Jogindernagar", "Nurpur", "Dalhousie"
    ],
    "Jharkhand": [
        "Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh", "Giridih", "Ramgarh",
        "Deoghar", "Dumka", "Chaibasa", "Phusro", "Medininagar", "Chirkunda", "Sindri",
        "Gumla", "Sahibganj", "Godda", "Pakur", "Koderma", "Lohardaga", "Jamtara"
    ],
    "Karnataka": [
        "Bangalore", "Mysore", "Mangalore", "Hubli", "Belgaum", "Davangere", "Bellary", "Tumkur",
        "Shimoga", "Gulbarga", "Bidar", "Hassan", "Udupi", "Raichur", "Bijapur", "Chitradurga",
        "Mandya", "Kolar", "Bagalkot", "Gadag", "Chikmagalur", "Karwar", "Hospet", "Bhadravati",
        "Ranibennur", "Sirsi", "Haveri", "Yadgir", "Koppal", "Ramanagara", "Vijayapura", "Manipal", "Surathkal"
    ],
    "Kerala": [
        "Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Palakkad", "Alappuzha",
        "Malappuram", "Kannur", "Kasaragod", "Kottayam", "Pathanamthitta", "Idukki", "Ernakulam",
        "Wayanad", "Thalassery", "Tirur", "Ponnani", "Kayamkulam", "Kottakkal", "Changanassery",
        "Manjeri", "Perinthalmanna", "Nilambur", "Attingal", "Cherthala", "Guruvayur"
    ],
    "Madhya Pradesh": [
        "Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain", "Sagar", "Dewas", "Satna",
        "Ratlam", "Rewa", "Murwara", "Singrauli", "Burhanpur", "Khandwa", "Morena", "Bhind",
        "Chhindwara", "Guna", "Shivpuri", "Vidisha", "Chhatarpur", "Damoh", "Mandsaur",
        "Khargone", "Neemuch", "Pithampur", "Hoshangabad", "Itarsi", "Sehore", "Betul",
        "Seoni", "Datia", "Nagda", "Dhar", "Barwani"
    ],
    "Maharashtra": [
        "Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Thane", "Solapur", "Amravati",
        "Kolhapur", "Nanded", "Sangli", "Akola", "Latur", "Jalgaon", "Ahmednagar", "Chandrapur",
        "Parbhani", "Ichalkaranji", "Jalna", "Bhusawal", "Panvel", "Satara", "Beed", "Yavatmal",
        "Kamptee", "Gondia", "Barshi", "Osmanabad", "Wardha", "Udgir", "Hinganghat",
        "Vita", "Buldhana", "Navi Mumbai", "Ulhasnagar", "Vasai-Virar", "Mira-Bhayandar",
        "Kalyan-Dombivli", "Bhiwandi", "Pimpri-Chinchwad", "Malegaon", "Dhule"
    ],
    "Manipur": [
        "Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Kakching", "Ukhrul", "Senapati",
        "Tamenglong", "Chandel", "Jiribam", "Moreh", "Yairipok", "Wangjing", "Mayang Imphal"
    ],
    "Meghalaya": [
        "Shillong", "Tura", "Jowai", "Nongpoh", "Williamnagar", "Baghmara", "Nongstoin",
        "Resubelpara", "Mairang", "Cherrapunji", "Mawkyrwat"
    ],
    "Mizoram": [
        "Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib", "Saiha", "Lawngtlai",
        "Mamit", "Tlabung", "Khawzawl", "Vairengte"
    ],
    "Nagaland": [
        "Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha", "Zunheboto", "Phek",
        "Mon", "Kiphire", "Longleng", "Peren", "Chumukedima"
    ],
    "Odisha": [
        "Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Balasore",
        "Bhadrak", "Baripada", "Jeypore", "Barbil", "Jharsuguda", "Rayagada", "Balangir",
        "Angul", "Bargarh", "Kendujhar", "Dhenkanal", "Paradip", "Jajpur", "Kendrapara",
        "Sunabeda", "Bhawanipatna", "Koraput", "Phulbani", "Gunupur", "Brahmapur"
    ],
    "Punjab": [
        "Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali",
        "Pathankot", "Hoshiarpur", "Moga", "Batala", "Kapurthala", "Khanna", "Malerkotla",
        "Abohar", "Muktsar", "Barnala", "Rajpura", "Firozpur", "Phagwara", "Sangrur",
        "Faridkot", "Mansa", "Fazilka", "Rupnagar", "Fatehgarh Sahib", "Gurdaspur", "Chandigarh"
    ],
    "Rajasthan": [
        "Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer", "Bikaner", "Alwar", "Bharatpur",
        "Bhilwara", "Sikar", "Pali", "Sri Ganganagar", "Tonk", "Kishangarh", "Beawar",
        "Hanumangarh", "Churu", "Nagaur", "Jhunjhunu", "Chittorgarh", "Sawai Madhopur",
        "Bundi", "Jhalawar", "Barmer", "Jaisalmer", "Banswara", "Dungarpur", "Dausa",
        "Karauli", "Pratapgarh", "Rajsamand", "Sirohi", "Dholpur", "Pilani"
    ],
    "Sikkim": [
        "Gangtok", "Namchi", "Mangan", "Gyalshing", "Rangpo", "Jorethang", "Singtam",
        "Pelling", "Ravangla", "Yuksom"
    ],
    "Tamil Nadu": [
        "Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Tiruppur",
        "Erode", "Vellore", "Thoothukudi", "Dindigul", "Thanjavur", "Karur", "Kancheepuram",
        "Nagercoil", "Kumbakonam", "Cuddalore", "Krishnagiri", "Dharmapuri", "Namakkal",
        "Pudukkottai", "Ramanathapuram", "Sivakasi", "Virudhunagar", "Ambur", "Pollachi",
        "Hosur", "Tiruvannamalai", "Neyveli", "Nagapattinam", "Mayiladuthurai", "Palani",
        "Ooty", "Arakkonam", "Chengalpattu", "Tirupattur", "Tenkasi", "Ranipet"
    ],
    "Telangana": [
        "Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Ramagundam", "Mahbubnagar",
        "Nalgonda", "Adilabad", "Suryapet", "Miryalaguda", "Jagtial", "Mancherial", "Nirmal",
        "Kamareddy", "Siddipet", "Sangareddy", "Vikarabad", "Wanaparthy", "Gadwal", "Nagarkurnool",
        "Sircilla", "Bhongir", "Jangaon", "Peddapalli", "Kothagudem", "Palwancha"
    ],
    "Tripura": [
        "Agartala", "Udaipur", "Dharmanagar", "Kailasahar", "Ambassa", "Belonia",
        "Sabroom", "Khowai", "Teliamura", "Amarpur", "Sonamura", "Kumarghat"
    ],
    "Uttar Pradesh": [
        "Lucknow", "Kanpur", "Agra", "Varanasi", "Noida", "Ghaziabad", "Meerut", "Allahabad",
        "Bareilly", "Aligarh", "Moradabad", "Saharanpur", "Gorakhpur", "Firozabad", "Jhansi",
        "Muzaffarnagar", "Mathura", "Rampur", "Shahjahanpur", "Farrukhabad", "Maunath Bhanjan",
        "Hapur", "Ayodhya", "Etawah", "Mirzapur", "Bulandshahr", "Sambhal", "Amroha", "Hardoi",
        "Fatehpur", "Raebareli", "Orai", "Sitapur", "Bahraich", "Modinagar", "Unnao", "Jaunpur",
        "Lakhimpur", "Hathras", "Budaun", "Chandausi", "Sultanpur", "Mainpuri", "Lalitpur",
        "Etah", "Deoria", "Gonda", "Basti", "Azamgarh", "Ballia", "Maharajganj", "Kushinagar"
    ],
    "Uttarakhand": [
        "Dehradun", "Haridwar", "Rishikesh", "Roorkee", "Haldwani", "Rudrapur", "Kashipur",
        "Nainital", "Mussoorie", "Pithoragarh", "Almora", "Bageshwar", "Champawat", "Pauri",
        "Tehri", "Uttarkashi", "Rudraprayag", "Chamoli", "Kotdwar", "Ramnagar", "Tanakpur",
        "Jaspur", "Sitarganj", "Kichha", "Manglaur"
    ],
    "West Bengal": [
        "Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Bardhaman", "Malda",
        "Baharampur", "Habra", "Kharagpur", "Shantipur", "Dankuni", "Dhulian", "Ranaghat",
        "Haldia", "Raiganj", "Krishnanagar", "Nabadwip", "Medinipur", "Jalpaiguri",
        "Balurghat", "Bankura", "Darjeeling", "Alipurduar", "Purulia", "Jangipur",
        "Bolpur", "Bangaon", "Cooch Behar", "Barasat", "Basirhat", "Bongaon", "Tamluk"
    ],
    "Andaman and Nicobar Islands": [
        "Port Blair", "Diglipur", "Mayabunder", "Rangat", "Car Nicobar", "Hut Bay"
    ],
    "Chandigarh": [
        "Chandigarh"
    ],
    "Dadra and Nagar Haveli and Daman and Diu": [
        "Daman", "Diu", "Silvassa", "Amli", "Dadra"
    ],
    "Delhi": [
        "New Delhi", "North Delhi", "South Delhi", "East Delhi", "West Delhi",
        "Central Delhi", "North East Delhi", "North West Delhi", "South East Delhi",
        "South West Delhi", "Shahdara", "Dwarka", "Rohini"
    ],
    "Jammu and Kashmir": [
        "Srinagar", "Jammu", "Anantnag", "Baramulla", "Budgam", "Pulwama", "Kupwara",
        "Shopian", "Ganderbal", "Bandipora", "Udhampur", "Kathua", "Doda", "Ramban",
        "Kishtwar", "Poonch", "Rajouri", "Reasi", "Samba"
    ],
    "Ladakh": [
        "Leh", "Kargil", "Nubra", "Zanskar", "Dras", "Diskit"
    ],
    "Lakshadweep": [
        "Kavaratti", "Agatti", "Minicoy", "Amini", "Andrott", "Kalpeni"
    ],
    "Puducherry": [
        "Puducherry", "Karaikal", "Mahe", "Yanam", "Ozhukarai"
    ]
}

# ==================== COLLEGES ====================
# Comprehensive Indian Engineering Colleges Database organized by State
# Format: {"name": "College Name", "state": "State", "city": "City", "type": "Govt/Private/Deemed"}

COLLEGES = [
    {"name": "AAA College of Engineering and Technology", "state": "Tamil Nadu", "city": "Sivakasi", "type": "Private"},
    {"name": "ABES Engineering College", "state": "Uttar Pradesh", "city": "Ghaziabad", "type": "Private"},
    {"name": "ABES Engineering College Ghaziabad", "state": "Uttar Pradesh", "city": "Ghaziabad", "type": "Private"},
    {"name": "AISSMS College of Engineering Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "APJ Abdul Kalam Technological University", "state": "Kerala", "city": "Thiruvananthapuram", "type": "Govt"},
    {"name": "AVN Institute of Engineering Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "AVS Engineering College", "state": "Tamil Nadu", "city": "Salem", "type": "Private"},
    {"name": "Acharya Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Acharya Nagarjuna University College of Engineering", "state": "Andhra Pradesh", "city": "Guntur", "type": "Govt"},
    {"name": "Acropolis Institute of Technology Indore", "state": "Madhya Pradesh", "city": "Indore", "type": "Private"},
    {"name": "Adhiyamaan College of Engineering", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Adhiyamaan College of Engineering", "state": "Tamil Nadu", "city": "Hosur", "type": "Private"},
    {"name": "Adithya Institute of Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Agni College of Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Agra University", "state": "Uttar Pradesh", "city": "Agra", "type": "Govt"},
    {"name": "Ajay Kumar Garg Engineering College Ghaziabad", "state": "Uttar Pradesh", "city": "Ghaziabad", "type": "Private"},
    {"name": "Akshaya College of Engineering and Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Alagappa College of Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Govt"},
    {"name": "Aligarh Muslim University", "state": "Uttar Pradesh", "city": "Aligarh", "type": "Govt"},
    {"name": "Allahabad University", "state": "Uttar Pradesh", "city": "Allahabad", "type": "Govt"},
    {"name": "Alpha College of Engineering", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Amity University Gurugram", "state": "Haryana", "city": "Gurugram", "type": "Private"},
    {"name": "Amity University Noida", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "Amrita Vishwa Vidyapeetham", "state": "Kerala", "city": "Kollam", "type": "Deemed"},
    {"name": "Amrita Vishwa Vidyapeetham", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Deemed"},
    {"name": "Anand Institute of Higher Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Andhra University College of Engineering", "state": "Andhra Pradesh", "city": "Visakhapatnam", "type": "Govt"},
    {"name": "Anil Neerukonda Institute of Technology", "state": "Andhra Pradesh", "city": "Visakhapatnam", "type": "Private"},
    {"name": "Anjalai Ammal Mahalingam Engineering College", "state": "Tamil Nadu", "city": "Tiruvannamalai", "type": "Private"},
    {"name": "Anna University", "state": "Tamil Nadu", "city": "Chennai", "type": "Govt"},
    {"name": "Anna University Regional Campus Madurai", "state": "Tamil Nadu", "city": "Madurai", "type": "Govt"},
    {"name": "Annamacharya Institute of Technology and Sciences", "state": "Andhra Pradesh", "city": "Tirupati", "type": "Private"},
    {"name": "Annamalai University", "state": "Tamil Nadu", "city": "Chidambaram", "type": "Govt"},
    {"name": "Anurag Group of Institutions Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Apex Institute of Engineering Jaipur", "state": "Rajasthan", "city": "Jaipur", "type": "Private"},
    {"name": "Arunai Engineering College", "state": "Tamil Nadu", "city": "Tiruvannamalai", "type": "Private"},
    {"name": "Arya College of Engineering Jaipur", "state": "Rajasthan", "city": "Jaipur", "type": "Private"},
    {"name": "Aryabhatta Knowledge University", "state": "Bihar", "city": "Patna", "type": "Govt"},
    {"name": "Asansol Engineering College Asansol", "state": "West Bengal", "city": "Asansol", "type": "Govt"},
    {"name": "Assam Engineering College", "state": "Assam", "city": "Guwahati", "type": "Govt"},
    {"name": "Assam University", "state": "Assam", "city": "Silchar", "type": "Govt"},
    {"name": "Atharva College of Engineering Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Atria Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Aurora's Engineering College Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Avanthi Institute of Engineering and Technology", "state": "Andhra Pradesh", "city": "Visakhapatnam", "type": "Private"},
    {"name": "BBDNITM Lucknow", "state": "Uttar Pradesh", "city": "Lucknow", "type": "Private"},
    {"name": "BIT Sindri Dhanbad", "state": "Jharkhand", "city": "Dhanbad", "type": "Govt"},
    {"name": "BITS Pilani Goa Campus", "state": "Maharashtra", "city": "Sanquelim", "type": "Private"},
    {"name": "BMS College of Engineering", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "BMS College of Engineering Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "BMS Institute of Technology and Management Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "BMSCE Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "BS Abdur Rahman Crescent Institute of Science and Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Deemed"},
    {"name": "BVRIT Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Bakhtiyarpur College of Engineering Patna", "state": "Bihar", "city": "Patna", "type": "Govt"},
    {"name": "Banaras Hindu University", "state": "Uttar Pradesh", "city": "Varanasi", "type": "Govt"},
    {"name": "Banasthali Vidyapith", "state": "Rajasthan", "city": "Tonk", "type": "Deemed"},
    {"name": "Bangalore Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Bangalore University", "state": "Karnataka", "city": "Bangalore", "type": "Govt"},
    {"name": "Bannari Amman Institute of Technology", "state": "Tamil Nadu", "city": "Erode", "type": "Private"},
    {"name": "Bapatla Engineering College", "state": "Andhra Pradesh", "city": "Bapatla", "type": "Govt"},
    {"name": "Barkatullah University", "state": "Madhya Pradesh", "city": "Bhopal", "type": "Govt"},
    {"name": "Bengal Engineering and Science University", "state": "West Bengal", "city": "Howrah", "type": "Govt"},
    {"name": "Bengal Institute of Technology Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Berhampur University", "state": "Odisha", "city": "Berhampur", "type": "Govt"},
    {"name": "Bhagalpur College of Engineering", "state": "Bihar", "city": "Bhagalpur", "type": "Govt"},
    {"name": "Bharath Institute of Higher Education and Research", "state": "Tamil Nadu", "city": "Chennai", "type": "Deemed"},
    {"name": "Bharathidasan Institute of Technology", "state": "Tamil Nadu", "city": "Tiruchirappalli", "type": "Govt"},
    {"name": "Bharati Vidyapeeth College of Engineering Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Bharati Vidyapeeth's College of Engineering for Women Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Bhaskar Engineering College Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Bhoj Reddy Engineering College for Women Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Bihar Institute of Technology", "state": "Bihar", "city": "Patna", "type": "Govt"},
    {"name": "Birla Institute of Technology Mesra", "state": "Jharkhand", "city": "Ranchi", "type": "Deemed"},
    {"name": "Birla Institute of Technology and Science Goa", "state": "Goa", "city": "Sanquelim", "type": "Private"},
    {"name": "Birla Institute of Technology and Science Pilani", "state": "Rajasthan", "city": "Pilani", "type": "Deemed"},
    {"name": "Birla Vishvakarma Mahavidyalaya Anand", "state": "Gujarat", "city": "Anand", "type": "Private"},
    {"name": "Buddha Institute of Technology Gorakhpur", "state": "Uttar Pradesh", "city": "Gorakhpur", "type": "Private"},
    {"name": "Builders Engineering College", "state": "Tamil Nadu", "city": "Kangeyam", "type": "Private"},
    {"name": "Bundelkhand Institute of Engineering Jhansi", "state": "Uttar Pradesh", "city": "Jhansi", "type": "Private"},
    {"name": "C.Abdul Hakeem College of Engineering and Technology", "state": "Tamil Nadu", "city": "Vellore", "type": "Private"},
    {"name": "CBIT Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "CGC Landran Mohali", "state": "Punjab", "city": "Mohali", "type": "Private"},
    {"name": "CK College of Engineering and Technology", "state": "Tamil Nadu", "city": "Cuddalore", "type": "Private"},
    {"name": "CMR Engineering College Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "CMR Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "CMR Institute of Technology Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "CMR Technical Campus Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "CMRIT Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "CSI Institute of Technology", "state": "Tamil Nadu", "city": "Nagercoil", "type": "Private"},
    {"name": "CV Raman College of Engineering Bhubaneswar", "state": "Odisha", "city": "Bhubaneswar", "type": "Private"},
    {"name": "CVR College of Engineering", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Calcutta University", "state": "West Bengal", "city": "Kolkata", "type": "Govt"},
    {"name": "Calicut University", "state": "Kerala", "city": "Kozhikode", "type": "Govt"},
    {"name": "Cambridge Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Camellia Institute of Technology Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Central University of Kashmir", "state": "Jammu and Kashmir", "city": "Srinagar", "type": "Govt"},
    {"name": "Centurion University", "state": "Andhra Pradesh", "city": "Visakhapatnam", "type": "Private"},
    {"name": "Centurion University Bhubaneswar", "state": "Odisha", "city": "Bhubaneswar", "type": "Private"},
    {"name": "Chaibasa Engineering College Chaibasa", "state": "Jharkhand", "city": "Chaibasa", "type": "Govt"},
    {"name": "Chebrolu Engineering College", "state": "Andhra Pradesh", "city": "Guntur", "type": "Private"},
    {"name": "Chennai Institute of Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Chettinad College of Engineering and Technology", "state": "Tamil Nadu", "city": "Karur", "type": "Private"},
    {"name": "Chhattisgarh Swami Vivekanand Technical University", "state": "Chhattisgarh", "city": "Bhilai", "type": "Govt"},
    {"name": "Chirala Engineering College", "state": "Andhra Pradesh", "city": "Chirala", "type": "Private"},
    {"name": "Chitkara University", "state": "Himachal Pradesh", "city": "Solan", "type": "Private"},
    {"name": "Chitkara University Punjab", "state": "Punjab", "city": "Rajpura", "type": "Private"},
    {"name": "Chitkara University Rajpura", "state": "Punjab", "city": "Rajpura", "type": "Private"},
    {"name": "Christian Medical College", "state": "Tamil Nadu", "city": "Vellore", "type": "Deemed"},
    {"name": "Cochin University of Science and Technology", "state": "Kerala", "city": "Kochi", "type": "Govt"},
    {"name": "Coimbatore Institute of Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "College of Engineering Guindy", "state": "Tamil Nadu", "city": "Chennai", "type": "Govt"},
    {"name": "College of Engineering Pune", "state": "Maharashtra", "city": "Pune", "type": "Govt"},
    {"name": "College of Engineering Trivandrum", "state": "Kerala", "city": "Thiruvananthapuram", "type": "Govt"},
    {"name": "College of Engineering and Technology Bhubaneswar", "state": "Odisha", "city": "Bhubaneswar", "type": "Govt"},
    {"name": "Cummins College of Engineering", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "D Y Patil College of Engineering Akurdi", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "DA-IICT Gandhinagar", "state": "Gujarat", "city": "Gandhinagar", "type": "Govt"},
    {"name": "DAVIET Jalandhar", "state": "Punjab", "city": "Jalandhar", "type": "Private"},
    {"name": "DCRUST Murthal", "state": "Haryana", "city": "Sonipat", "type": "Govt"},
    {"name": "DIT University", "state": "Uttarakhand", "city": "Dehradun", "type": "Private"},
    {"name": "DJ Sanghvi College of Engineering", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "DVR & Dr HS MIC College of Technology", "state": "Andhra Pradesh", "city": "Kanchikacherla", "type": "Private"},
    {"name": "DY Patil College of Engineering Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Darbhanga College of Engineering Darbhanga", "state": "Bihar", "city": "Darbhanga", "type": "Govt"},
    {"name": "Dayananda Sagar College of Engineering", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Dayananda Sagar College of Engineering Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Deenbandhu Chhotu Ram University", "state": "Haryana", "city": "Sonipat", "type": "Govt"},
    {"name": "Delhi Technological University", "state": "Delhi", "city": "New Delhi", "type": "Govt"},
    {"name": "Devi Ahilya Vishwavidyalaya", "state": "Madhya Pradesh", "city": "Indore", "type": "Govt"},
    {"name": "Dhanalakshmi Srinivasan Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Dhanekula Institute of Engineering and Technology", "state": "Andhra Pradesh", "city": "Vijayawada", "type": "Private"},
    {"name": "Dharmsinh Desai University Nadiad", "state": "Gujarat", "city": "Nadiad", "type": "Private"},
    {"name": "Dhirajlal Gandhi College of Technology", "state": "Tamil Nadu", "city": "Salem", "type": "Private"},
    {"name": "Dhirubhai Ambani Institute of Information and Communication Technology", "state": "Gujarat", "city": "Gandhinagar", "type": "Govt"},
    {"name": "Dhole Patil College of Engineering Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Dibrugarh University", "state": "Assam", "city": "Dibrugarh", "type": "Govt"},
    {"name": "Don Bosco Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Dr. APJ Abdul Kalam Technical University", "state": "Uttar Pradesh", "city": "Lucknow", "type": "Govt"},
    {"name": "Dr. Ambedkar Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Dr. BC Roy Engineering College Durgapur", "state": "West Bengal", "city": "Durgapur", "type": "Govt"},
    {"name": "Dr. Babasaheb Ambedkar Technological University", "state": "Maharashtra", "city": "Lonere", "type": "Govt"},
    {"name": "Dr. MGR Educational and Research Institute", "state": "Tamil Nadu", "city": "Chennai", "type": "Deemed"},
    {"name": "Dr. Mahalingam College of Engineering and Technology", "state": "Tamil Nadu", "city": "Pollachi", "type": "Private"},
    {"name": "Dr. Sivanthi Aditanar College of Engineering", "state": "Tamil Nadu", "city": "Thoothukudi", "type": "Private"},
    {"name": "Dronacharya College of Engineering Noida", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "Durgapur Institute of Advanced Technology Durgapur", "state": "West Bengal", "city": "Durgapur", "type": "Private"},
    {"name": "East West Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Easwari Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Einstein College of Engineering", "state": "Tamil Nadu", "city": "Tirunelveli", "type": "Private"},
    {"name": "Er. Perumal Manimekalai College of Engineering", "state": "Tamil Nadu", "city": "Hosur", "type": "Private"},
    {"name": "Excel Engineering College", "state": "Tamil Nadu", "city": "Namakkal", "type": "Private"},
    {"name": "Federal Institute of Science Angamaly", "state": "Kerala", "city": "Kochi", "type": "Private"},
    {"name": "Fr. Conceicao Rodrigues College of Engineering Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Francis Xavier Engineering College", "state": "Tamil Nadu", "city": "Tirunelveli", "type": "Private"},
    {"name": "Future Institute of Engineering Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "G Narayanamma Institute of Technology Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "G Pullaiah College of Engineering and Technology", "state": "Andhra Pradesh", "city": "Kurnool", "type": "Private"},
    {"name": "GH Patel College of Engineering Anand", "state": "Gujarat", "city": "Anand", "type": "Private"},
    {"name": "GITAM University", "state": "Andhra Pradesh", "city": "Visakhapatnam", "type": "Deemed"},
    {"name": "GL Bajaj Institute of Technology Noida", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "GNDEC Ludhiana", "state": "Punjab", "city": "Ludhiana", "type": "Govt"},
    {"name": "GNDU Regional Campus Jalandhar", "state": "Punjab", "city": "Jalandhar", "type": "Govt"},
    {"name": "Galgotias College of Engineering Greater Noida", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "Gandhi Engineering College Bhubaneswar", "state": "Odisha", "city": "Bhubaneswar", "type": "Private"},
    {"name": "Gandhi Institute of Engineering Bhubaneswar", "state": "Odisha", "city": "Bhubaneswar", "type": "Private"},
    {"name": "Gauhati University", "state": "Assam", "city": "Guwahati", "type": "Govt"},
    {"name": "Gautam Buddha University", "state": "Uttar Pradesh", "city": "Noida", "type": "Govt"},
    {"name": "Gaya College of Engineering Gaya", "state": "Bihar", "city": "Gaya", "type": "Govt"},
    {"name": "Gayatri Vidya Parishad College of Engineering", "state": "Andhra Pradesh", "city": "Visakhapatnam", "type": "Private"},
    {"name": "Geethanjali College of Engineering Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Girijananda Chowdhury Institute Guwahati", "state": "Assam", "city": "Guwahati", "type": "Private"},
    {"name": "Global Academy of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Global Institute of Technology Jaipur", "state": "Rajasthan", "city": "Jaipur", "type": "Private"},
    {"name": "Gnanamani College of Technology", "state": "Tamil Nadu", "city": "Namakkal", "type": "Private"},
    {"name": "Goa Engineering College", "state": "Goa", "city": "Ponda", "type": "Govt"},
    {"name": "Goa University", "state": "Goa", "city": "Panaji", "type": "Govt"},
    {"name": "Godavari Institute of Engineering and Technology", "state": "Andhra Pradesh", "city": "Rajahmundry", "type": "Private"},
    {"name": "Gogte Institute of Technology Belgaum", "state": "Karnataka", "city": "Belgaum", "type": "Private"},
    {"name": "Gokaraju Rangaraju Institute of Engineering Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Government College of Engineering Aurangabad", "state": "Maharashtra", "city": "Aurangabad", "type": "Govt"},
    {"name": "Government College of Engineering Bargur", "state": "Tamil Nadu", "city": "Krishnagiri", "type": "Govt"},
    {"name": "Government College of Engineering Karad", "state": "Maharashtra", "city": "Satara", "type": "Govt"},
    {"name": "Government College of Engineering Salem", "state": "Tamil Nadu", "city": "Salem", "type": "Govt"},
    {"name": "Government College of Engineering Tirunelveli", "state": "Tamil Nadu", "city": "Tirunelveli", "type": "Govt"},
    {"name": "Government College of Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Govt"},
    {"name": "Government Engineering College Gandhinagar", "state": "Gujarat", "city": "Gandhinagar", "type": "Govt"},
    {"name": "Government Engineering College Thrissur", "state": "Kerala", "city": "Thrissur", "type": "Govt"},
    {"name": "Govind Ballabh Pant University of Agriculture and Technology", "state": "Uttarakhand", "city": "Rudrapur", "type": "Govt"},
    {"name": "Govindram Seksaria Institute of Technology Indore", "state": "Madhya Pradesh", "city": "Indore", "type": "Private"},
    {"name": "Graphic Era University", "state": "Uttarakhand", "city": "Dehradun", "type": "Deemed"},
    {"name": "Greater Noida Institute of Technology", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "Gujarat Technological University", "state": "Gujarat", "city": "Ahmedabad", "type": "Govt"},
    {"name": "Gujarat University", "state": "Gujarat", "city": "Ahmedabad", "type": "Govt"},
    {"name": "Gulbarga University", "state": "Karnataka", "city": "Gulbarga", "type": "Govt"},
    {"name": "Guru Ghasidas University", "state": "Chhattisgarh", "city": "Bilaspur", "type": "Govt"},
    {"name": "Guru Jambheshwar University", "state": "Haryana", "city": "Hisar", "type": "Govt"},
    {"name": "Guru Nanak Dev Engineering College Ludhiana", "state": "Punjab", "city": "Ludhiana", "type": "Private"},
    {"name": "Guru Nanak Dev University", "state": "Punjab", "city": "Amritsar", "type": "Govt"},
    {"name": "Guru Nanak Institutions Technical Campus Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Gurunanak Institute of Technology Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "HITAM Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "HKBK College of Engineering Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Haldia Institute of Technology Haldia", "state": "West Bengal", "city": "Haldia", "type": "Private"},
    {"name": "Harcourt Butler Technical University", "state": "Uttar Pradesh", "city": "Kanpur", "type": "Govt"},
    {"name": "Hemvati Nandan Bahuguna Garhwal University", "state": "Uttarakhand", "city": "Pauri", "type": "Govt"},
    {"name": "Heritage Institute of Technology", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Heritage Institute of Technology Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Himachal Pradesh University", "state": "Himachal Pradesh", "city": "Shimla", "type": "Govt"},
    {"name": "Hindustan Institute of Technology and Science", "state": "Tamil Nadu", "city": "Chennai", "type": "Deemed"},
    {"name": "Hindusthan College of Engineering and Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Holy Mary Institute of Technology Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "IIMT Engineering College Meerut", "state": "Uttar Pradesh", "city": "Meerut", "type": "Private"},
    {"name": "IMS Engineering College Ghaziabad", "state": "Uttar Pradesh", "city": "Ghaziabad", "type": "Private"},
    {"name": "IPS Academy Indore", "state": "Madhya Pradesh", "city": "Indore", "type": "Private"},
    {"name": "ITER SOA University Bhubaneswar", "state": "Odisha", "city": "Bhubaneswar", "type": "Deemed"},
    {"name": "ITM University Gurgaon", "state": "Haryana", "city": "Gurugram", "type": "Private"},
    {"name": "ITS Engineering College Greater Noida", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "Imperial College of Engineering and Research Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Indian Institute of Engineering Science and Technology", "state": "West Bengal", "city": "Howrah", "type": "Govt"},
    {"name": "Indian Institute of Information Technology Allahabad", "state": "Uttar Pradesh", "city": "Allahabad", "type": "Govt"},
    {"name": "Indian Institute of Information Technology Gwalior", "state": "Madhya Pradesh", "city": "Gwalior", "type": "Govt"},
    {"name": "Indian Institute of Information Technology Jabalpur", "state": "Madhya Pradesh", "city": "Jabalpur", "type": "Govt"},
    {"name": "Indian Institute of Information Technology Naya Raipur", "state": "Chhattisgarh", "city": "Raipur", "type": "Govt"},
    {"name": "Indian Institute of Science Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Govt"},
    {"name": "Indian Institute of Technology (ISM) Dhanbad", "state": "Jharkhand", "city": "Dhanbad", "type": "Govt"},
    {"name": "Indian Institute of Technology BHU", "state": "Uttar Pradesh", "city": "Varanasi", "type": "Govt"},
    {"name": "Indian Institute of Technology Bhubaneswar", "state": "Odisha", "city": "Bhubaneswar", "type": "Govt"},
    {"name": "Indian Institute of Technology Bombay", "state": "Maharashtra", "city": "Mumbai", "type": "Govt"},
    {"name": "Indian Institute of Technology Delhi", "state": "Delhi", "city": "New Delhi", "type": "Govt"},
    {"name": "Indian Institute of Technology Dharwad", "state": "Karnataka", "city": "Dharwad", "type": "Govt"},
    {"name": "Indian Institute of Technology Gandhinagar", "state": "Gujarat", "city": "Gandhinagar", "type": "Govt"},
    {"name": "Indian Institute of Technology Guwahati", "state": "Assam", "city": "Guwahati", "type": "Govt"},
    {"name": "Indian Institute of Technology Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Govt"},
    {"name": "Indian Institute of Technology Indore", "state": "Madhya Pradesh", "city": "Indore", "type": "Govt"},
    {"name": "Indian Institute of Technology Jodhpur", "state": "Rajasthan", "city": "Jodhpur", "type": "Govt"},
    {"name": "Indian Institute of Technology Jodhpur Extension", "state": "Haryana", "city": "Karnal", "type": "Govt"},
    {"name": "Indian Institute of Technology Kanpur", "state": "Uttar Pradesh", "city": "Kanpur", "type": "Govt"},
    {"name": "Indian Institute of Technology Kharagpur", "state": "West Bengal", "city": "Kharagpur", "type": "Govt"},
    {"name": "Indian Institute of Technology Madras", "state": "Tamil Nadu", "city": "Chennai", "type": "Govt"},
    {"name": "Indian Institute of Technology Mandi", "state": "Himachal Pradesh", "city": "Mandi", "type": "Govt"},
    {"name": "Indian Institute of Technology Nagpur", "state": "Maharashtra", "city": "Nagpur", "type": "Govt"},
    {"name": "Indian Institute of Technology Palakkad", "state": "Kerala", "city": "Palakkad", "type": "Govt"},
    {"name": "Indian Institute of Technology Patna", "state": "Bihar", "city": "Patna", "type": "Govt"},
    {"name": "Indian Institute of Technology Roorkee", "state": "Uttarakhand", "city": "Roorkee", "type": "Govt"},
    {"name": "Indian Institute of Technology Ropar", "state": "Punjab", "city": "Rupnagar", "type": "Govt"},
    {"name": "Indian Institute of Technology Tirupati", "state": "Andhra Pradesh", "city": "Tirupati", "type": "Govt"},
    {"name": "Indira College of Engineering and Management Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Indira Gandhi Delhi Technical University for Women", "state": "Delhi", "city": "New Delhi", "type": "Govt"},
    {"name": "Indraprastha Institute of Information Technology", "state": "Delhi", "city": "New Delhi", "type": "Govt"},
    {"name": "Info Institute of Engineering", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Institute of Aeronautical Engineering Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Institute of Chemical Technology Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Govt"},
    {"name": "Institute of Engineering and Management Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "International Institute of Information Technology Bhubaneswar", "state": "Odisha", "city": "Bhubaneswar", "type": "Govt"},
    {"name": "International Institute of Information Technology Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Govt"},
    {"name": "Islamic University of Science and Technology", "state": "Jammu and Kashmir", "city": "Pulwama", "type": "Govt"},
    {"name": "J.J. College of Engineering and Technology", "state": "Tamil Nadu", "city": "Tiruchirappalli", "type": "Private"},
    {"name": "JCT College of Engineering and Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "JECRC University Jaipur", "state": "Rajasthan", "city": "Jaipur", "type": "Private"},
    {"name": "JIS College of Engineering Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "JNTU College of Engineering Anantapur", "state": "Andhra Pradesh", "city": "Anantapur", "type": "Govt"},
    {"name": "JNTU College of Engineering Kakinada", "state": "Andhra Pradesh", "city": "Kakinada", "type": "Govt"},
    {"name": "JNTU College of Engineering Pulivendula", "state": "Andhra Pradesh", "city": "Pulivendula", "type": "Govt"},
    {"name": "JNTUA College of Engineering Vizianagaram", "state": "Andhra Pradesh", "city": "Vizianagaram", "type": "Govt"},
    {"name": "JSPM's Rajarshi Shahu College of Engineering Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "JSS Academy of Technical Education", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "JSS Science and Technology University", "state": "Karnataka", "city": "Mysore", "type": "Private"},
    {"name": "Jadavpur University", "state": "West Bengal", "city": "Kolkata", "type": "Govt"},
    {"name": "Jai Narain Vyas University", "state": "Rajasthan", "city": "Jodhpur", "type": "Govt"},
    {"name": "Jaipur Engineering College Jaipur", "state": "Rajasthan", "city": "Jaipur", "type": "Private"},
    {"name": "Jamia Millia Islamia", "state": "Uttar Pradesh", "city": "Noida", "type": "Govt"},
    {"name": "Jamia Millia Islamia University", "state": "Delhi", "city": "New Delhi", "type": "Govt"},
    {"name": "Jawaharlal Nehru Technological University", "state": "Andhra Pradesh", "city": "Kakinada", "type": "Govt"},
    {"name": "Jawaharlal Nehru Technological University Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Govt"},
    {"name": "Jawaharlal Nehru University", "state": "Delhi", "city": "New Delhi", "type": "Govt"},
    {"name": "Jaya Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Jayaram College of Engineering and Technology", "state": "Tamil Nadu", "city": "Tiruchirappalli", "type": "Private"},
    {"name": "Jaypee University of Information Technology", "state": "Himachal Pradesh", "city": "Solan", "type": "Private"},
    {"name": "Jeppiaar Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Jerusalem College of Engineering", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Jiwaji University", "state": "Madhya Pradesh", "city": "Gwalior", "type": "Govt"},
    {"name": "Jorhat Engineering College", "state": "Assam", "city": "Jorhat", "type": "Govt"},
    {"name": "K. Ramakrishnan College of Engineering", "state": "Tamil Nadu", "city": "Tiruchirappalli", "type": "Private"},
    {"name": "K.S.R. College of Engineering", "state": "Tamil Nadu", "city": "Tiruchengode", "type": "Private"},
    {"name": "KCG College of Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "KIET Group of Institutions", "state": "Uttar Pradesh", "city": "Ghaziabad", "type": "Private"},
    {"name": "KIET Group of Institutions Ghaziabad", "state": "Uttar Pradesh", "city": "Ghaziabad", "type": "Private"},
    {"name": "KIIT University", "state": "Odisha", "city": "Bhubaneswar", "type": "Deemed"},
    {"name": "KIT-Kalaignarkarunanidhi Institute of Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "KJ Somaiya College of Engineering", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "KL University", "state": "Andhra Pradesh", "city": "Vijayawada", "type": "Deemed"},
    {"name": "KLE Technological University Hubli", "state": "Karnataka", "city": "Hubli", "type": "Private"},
    {"name": "KNIT Sultanpur", "state": "Uttar Pradesh", "city": "Sultanpur", "type": "Govt"},
    {"name": "KPR Institute of Engineering and Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "KSG College of Arts and Science", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "KSR College of Engineering", "state": "Tamil Nadu", "city": "Namakkal", "type": "Private"},
    {"name": "Kakatiya University", "state": "Telangana", "city": "Warangal", "type": "Govt"},
    {"name": "Kalaignar Karunanidhi Institute of Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Kalasalingam Academy of Research and Education", "state": "Tamil Nadu", "city": "Virudhunagar", "type": "Deemed"},
    {"name": "Kalinga University", "state": "Chhattisgarh", "city": "Raipur", "type": "Private"},
    {"name": "Kalyani Government Engineering College", "state": "West Bengal", "city": "Kalyani", "type": "Govt"},
    {"name": "Kamla Nehru Institute of Technology Sultanpur", "state": "Uttar Pradesh", "city": "Sultanpur", "type": "Govt"},
    {"name": "Kannur University", "state": "Kerala", "city": "Kannur", "type": "Govt"},
    {"name": "Karnatak University", "state": "Karnataka", "city": "Dharwad", "type": "Govt"},
    {"name": "Karpagam Academy of Higher Education", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Deemed"},
    {"name": "Karunya Institute of Technology and Sciences", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Deemed"},
    {"name": "Kathir College of Engineering", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Kerala University", "state": "Kerala", "city": "Thiruvananthapuram", "type": "Govt"},
    {"name": "Keshav Memorial Institute of Technology Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Kgisl Institute of Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Kings Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Kolhan University", "state": "Jharkhand", "city": "Chaibasa", "type": "Govt"},
    {"name": "Kongu Engineering College", "state": "Tamil Nadu", "city": "Erode", "type": "Private"},
    {"name": "Krishna Institute of Engineering Ghaziabad", "state": "Uttar Pradesh", "city": "Ghaziabad", "type": "Private"},
    {"name": "Kumaraguru College of Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Kumaun University", "state": "Uttarakhand", "city": "Nainital", "type": "Govt"},
    {"name": "Kurukshetra University", "state": "Haryana", "city": "Thanesar", "type": "Govt"},
    {"name": "LBS College of Engineering Kasaragod", "state": "Kerala", "city": "Kasaragod", "type": "Govt"},
    {"name": "LD College of Engineering", "state": "Gujarat", "city": "Ahmedabad", "type": "Govt"},
    {"name": "LNM Institute of Information Technology", "state": "Rajasthan", "city": "Jaipur", "type": "Deemed"},
    {"name": "Lakireddy Bali Reddy College of Engineering", "state": "Andhra Pradesh", "city": "Mylavaram", "type": "Private"},
    {"name": "Lakshmi Narain College of Technology Bhopal", "state": "Madhya Pradesh", "city": "Bhopal", "type": "Private"},
    {"name": "Lalit Narayan Mithila University", "state": "Bihar", "city": "Darbhanga", "type": "Govt"},
    {"name": "Lingayas Vidyapeeth Faridabad", "state": "Haryana", "city": "Faridabad", "type": "Private"},
    {"name": "Lokmanya Tilak College of Engineering Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Lovely Professional University", "state": "Punjab", "city": "Phagwara", "type": "Private"},
    {"name": "Lovely Professional University Jalandhar", "state": "Punjab", "city": "Phagwara", "type": "Private"},
    {"name": "Loyola-ICAM College of Engineering and Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Lucknow University", "state": "Uttar Pradesh", "city": "Lucknow", "type": "Govt"},
    {"name": "M. Kumarasamy College of Engineering", "state": "Tamil Nadu", "city": "Karur", "type": "Private"},
    {"name": "MCKV Institute of Engineering Howrah", "state": "West Bengal", "city": "Howrah", "type": "Private"},
    {"name": "MES College of Engineering Kuttippuram", "state": "Kerala", "city": "Malappuram", "type": "Private"},
    {"name": "MGIT Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "MIT Manipal", "state": "Karnataka", "city": "Manipal", "type": "Private"},
    {"name": "MIT World Peace University", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "MPEC Kanpur", "state": "Uttar Pradesh", "city": "Kanpur", "type": "Private"},
    {"name": "MS Ramaiah Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "MS University Vadodara", "state": "Gujarat", "city": "Vadodara", "type": "Govt"},
    {"name": "MSRIT Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "MVSR Engineering College", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Madanapalle Institute of Technology and Science", "state": "Andhra Pradesh", "city": "Madanapalle", "type": "Private"},
    {"name": "Madha Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Madras Institute of Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Govt"},
    {"name": "Magadh University", "state": "Bihar", "city": "Gaya", "type": "Govt"},
    {"name": "Maharana Pratap University of Agriculture and Technology", "state": "Rajasthan", "city": "Udaipur", "type": "Govt"},
    {"name": "Maharashtra Institute of Technology Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Maharshi Dayanand University", "state": "Haryana", "city": "Rohtak", "type": "Govt"},
    {"name": "Mahath Amma Institute of Engineering and Technology", "state": "Tamil Nadu", "city": "Pudukkottai", "type": "Private"},
    {"name": "Mahatma Gandhi Institute of Technology Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Mahatma Gandhi University", "state": "Kerala", "city": "Kottayam", "type": "Govt"},
    {"name": "Mahendra Engineering College", "state": "Tamil Nadu", "city": "Namakkal", "type": "Private"},
    {"name": "Mahendra Institute of Engineering and Technology", "state": "Tamil Nadu", "city": "Namakkal", "type": "Private"},
    {"name": "Mailam Engineering College", "state": "Tamil Nadu", "city": "Villupuram", "type": "Private"},
    {"name": "Malaviya National Institute of Technology Jaipur", "state": "Rajasthan", "city": "Jaipur", "type": "Govt"},
    {"name": "Malla Reddy College of Engineering Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Malla Reddy Engineering College Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Malla Reddy Institute of Engineering Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Malwa Institute of Technology Indore", "state": "Madhya Pradesh", "city": "Indore", "type": "Private"},
    {"name": "Manav Rachna University", "state": "Haryana", "city": "Faridabad", "type": "Private"},
    {"name": "Mangalore University", "state": "Karnataka", "city": "Mangalore", "type": "Govt"},
    {"name": "Manipal Academy of Higher Education", "state": "Karnataka", "city": "Manipal", "type": "Deemed"},
    {"name": "Manipal University Jaipur", "state": "Rajasthan", "city": "Jaipur", "type": "Private"},
    {"name": "Manipal University Jaipur", "state": "Rajasthan", "city": "Jaipur", "type": "Private"},
    {"name": "Manipur Technical University", "state": "Manipur", "city": "Imphal", "type": "Govt"},
    {"name": "Manipur University", "state": "Manipur", "city": "Imphal", "type": "Govt"},
    {"name": "Mar Athanasius College of Engineering Kothamangalam", "state": "Kerala", "city": "Kochi", "type": "Private"},
    {"name": "Marthandam College of Engineering and Technology", "state": "Tamil Nadu", "city": "Nagercoil", "type": "Private"},
    {"name": "Maulana Azad National Institute of Technology", "state": "Madhya Pradesh", "city": "Bhopal", "type": "Govt"},
    {"name": "Meenakshi College of Engineering", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Meenakshi Sundararajan Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Meghnad Saha Institute of Technology Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Mepco Schlenk Engineering College", "state": "Tamil Nadu", "city": "Sivakasi", "type": "Private"},
    {"name": "Methodist College of Engineering Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Miracle Educational Society Group of Institutions", "state": "Andhra Pradesh", "city": "Vizianagaram", "type": "Private"},
    {"name": "Mizoram University", "state": "Mizoram", "city": "Aizawl", "type": "Govt"},
    {"name": "Modi Institute of Technology Kota", "state": "Rajasthan", "city": "Kota", "type": "Private"},
    {"name": "Mohamed Sathak Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Mohanlal Sukhadia University", "state": "Rajasthan", "city": "Udaipur", "type": "Govt"},
    {"name": "Mookambigai College of Engineering", "state": "Tamil Nadu", "city": "Pudukottai", "type": "Private"},
    {"name": "Motilal Nehru National Institute of Technology Allahabad", "state": "Uttar Pradesh", "city": "Allahabad", "type": "Govt"},
    {"name": "Mumbai University", "state": "Maharashtra", "city": "Mumbai", "type": "Govt"},
    {"name": "Muthayammal Engineering College", "state": "Tamil Nadu", "city": "Namakkal", "type": "Private"},
    {"name": "Muzaffarpur Institute of Technology", "state": "Bihar", "city": "Muzaffarpur", "type": "Govt"},
    {"name": "NBN Sinhgad School of Engineering Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "NIE Mysore", "state": "Karnataka", "city": "Mysore", "type": "Govt"},
    {"name": "NMIT Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "NSS College of Engineering Palakkad", "state": "Kerala", "city": "Palakkad", "type": "Govt"},
    {"name": "Nagaland University", "state": "Nagaland", "city": "Kohima", "type": "Govt"},
    {"name": "Nagpur University", "state": "Maharashtra", "city": "Nagpur", "type": "Govt"},
    {"name": "Nalanda College of Engineering Bihar Sharif", "state": "Bihar", "city": "Bihar Sharif", "type": "Govt"},
    {"name": "Nandha College of Technology", "state": "Tamil Nadu", "city": "Erode", "type": "Private"},
    {"name": "Nandha Engineering College", "state": "Tamil Nadu", "city": "Erode", "type": "Private"},
    {"name": "Narasaraopeta Engineering College", "state": "Andhra Pradesh", "city": "Narasaraopet", "type": "Private"},
    {"name": "Narula Institute of Technology Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "National Institute of Technology Agartala", "state": "Tripura", "city": "Agartala", "type": "Govt"},
    {"name": "National Institute of Technology Andhra Pradesh", "state": "Andhra Pradesh", "city": "Tadepalligudem", "type": "Govt"},
    {"name": "National Institute of Technology Arunachal Pradesh", "state": "Arunachal Pradesh", "city": "Itanagar", "type": "Govt"},
    {"name": "National Institute of Technology Bhopal", "state": "Madhya Pradesh", "city": "Bhopal", "type": "Govt"},
    {"name": "National Institute of Technology Calicut", "state": "Kerala", "city": "Kozhikode", "type": "Govt"},
    {"name": "National Institute of Technology Durgapur", "state": "West Bengal", "city": "Durgapur", "type": "Govt"},
    {"name": "National Institute of Technology Goa", "state": "Goa", "city": "Ponda", "type": "Govt"},
    {"name": "National Institute of Technology Hamirpur", "state": "Himachal Pradesh", "city": "Hamirpur", "type": "Govt"},
    {"name": "National Institute of Technology Jaipur", "state": "Rajasthan", "city": "Jaipur", "type": "Govt"},
    {"name": "National Institute of Technology Jamshedpur", "state": "Jharkhand", "city": "Jamshedpur", "type": "Govt"},
    {"name": "National Institute of Technology Karnataka", "state": "Karnataka", "city": "Surathkal", "type": "Govt"},
    {"name": "National Institute of Technology Kurukshetra", "state": "Haryana", "city": "Thanesar", "type": "Govt"},
    {"name": "National Institute of Technology Manipur", "state": "Manipur", "city": "Imphal", "type": "Govt"},
    {"name": "National Institute of Technology Meghalaya", "state": "Meghalaya", "city": "Shillong", "type": "Govt"},
    {"name": "National Institute of Technology Mizoram", "state": "Mizoram", "city": "Aizawl", "type": "Govt"},
    {"name": "National Institute of Technology Nagaland", "state": "Nagaland", "city": "Dimapur", "type": "Govt"},
    {"name": "National Institute of Technology Patna", "state": "Bihar", "city": "Patna", "type": "Govt"},
    {"name": "National Institute of Technology Puducherry", "state": "Puducherry", "city": "Karaikal", "type": "Govt"},
    {"name": "National Institute of Technology Raipur", "state": "Chhattisgarh", "city": "Raipur", "type": "Govt"},
    {"name": "National Institute of Technology Rourkela", "state": "Odisha", "city": "Rourkela", "type": "Govt"},
    {"name": "National Institute of Technology Sikkim", "state": "Sikkim", "city": "Ravangla", "type": "Govt"},
    {"name": "National Institute of Technology Silchar", "state": "Assam", "city": "Silchar", "type": "Govt"},
    {"name": "National Institute of Technology Srinagar", "state": "Jammu and Kashmir", "city": "Srinagar", "type": "Govt"},
    {"name": "National Institute of Technology Surat", "state": "Gujarat", "city": "Surat", "type": "Govt"},
    {"name": "National Institute of Technology Tiruchirappalli", "state": "Tamil Nadu", "city": "Tiruchirappalli", "type": "Govt"},
    {"name": "National Institute of Technology Uttarakhand", "state": "Uttarakhand", "city": "Pauri", "type": "Govt"},
    {"name": "National Institute of Technology Warangal", "state": "Telangana", "city": "Warangal", "type": "Govt"},
    {"name": "Nehru Institute of Engineering and Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Neil Gogte Institute of Technology Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Netaji Subhas University of Technology", "state": "Delhi", "city": "New Delhi", "type": "Govt"},
    {"name": "New Horizon College of Engineering Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Nimra College of Engineering and Technology", "state": "Andhra Pradesh", "city": "Vijayawada", "type": "Private"},
    {"name": "Nirma University", "state": "Gujarat", "city": "Ahmedabad", "type": "Private"},
    {"name": "Nitte Meenakshi Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Noida Institute of Engineering Noida", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "North Bengal University", "state": "West Bengal", "city": "Siliguri", "type": "Govt"},
    {"name": "North Eastern Regional Institute of Science and Technology", "state": "Arunachal Pradesh", "city": "Itanagar", "type": "Govt"},
    {"name": "North Maharashtra University", "state": "Maharashtra", "city": "Jalgaon", "type": "Govt"},
    {"name": "North-Eastern Hill University", "state": "Meghalaya", "city": "Shillong", "type": "Govt"},
    {"name": "Oriental Institute of Science and Technology Bhopal", "state": "Madhya Pradesh", "city": "Bhopal", "type": "Private"},
    {"name": "Osmania University", "state": "Telangana", "city": "Hyderabad", "type": "Govt"},
    {"name": "Oxford College of Engineering Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "P.A. College of Engineering and Technology", "state": "Tamil Nadu", "city": "Pollachi", "type": "Private"},
    {"name": "PBR Visvodaya Institute of Technology", "state": "Andhra Pradesh", "city": "Kavali", "type": "Private"},
    {"name": "PDM College of Engineering Bahadurgarh", "state": "Haryana", "city": "Bahadurgarh", "type": "Private"},
    {"name": "PES University", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "PICT Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "PSCMR College of Engineering and Technology", "state": "Andhra Pradesh", "city": "Vijayawada", "type": "Private"},
    {"name": "PSG College of Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "PSG Institute of Technology and Applied Research", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "PSIT Kanpur", "state": "Uttar Pradesh", "city": "Kanpur", "type": "Private"},
    {"name": "Paavai Engineering College", "state": "Tamil Nadu", "city": "Namakkal", "type": "Private"},
    {"name": "Pallavan College of Engineering", "state": "Tamil Nadu", "city": "Kanchipuram", "type": "Private"},
    {"name": "Pandit Deendayal Petroleum University", "state": "Gujarat", "city": "Gandhinagar", "type": "Govt"},
    {"name": "Panimalar Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Panimalar Institute of Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Panjab University", "state": "Punjab", "city": "Chandigarh", "type": "Govt"},
    {"name": "Park College of Engineering and Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Patna University", "state": "Bihar", "city": "Patna", "type": "Govt"},
    {"name": "Periyar Maniammai Institute of Science and Technology", "state": "Tamil Nadu", "city": "Thanjavur", "type": "Deemed"},
    {"name": "Perunthalaivar Kamarajar Institute of Engineering and Technology", "state": "Tamil Nadu", "city": "Karaikal", "type": "Govt"},
    {"name": "Pillai College of Engineering Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Pondicherry Engineering College", "state": "Tamil Nadu", "city": "Puducherry", "type": "Govt"},
    {"name": "Pondicherry Engineering College", "state": "Puducherry", "city": "Puducherry", "type": "Govt"},
    {"name": "Pondicherry University", "state": "Puducherry", "city": "Puducherry", "type": "Govt"},
    {"name": "Poornima College of Engineering Jaipur", "state": "Rajasthan", "city": "Jaipur", "type": "Private"},
    {"name": "Pragati Engineering College", "state": "Andhra Pradesh", "city": "Kakinada", "type": "Private"},
    {"name": "Prathyusha Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Prince Shri Venkateshwara Padmavathy Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Priyadarshini College of Engineering Nagpur", "state": "Maharashtra", "city": "Nagpur", "type": "Private"},
    {"name": "Pt. Ravishankar Shukla University", "state": "Chhattisgarh", "city": "Raipur", "type": "Govt"},
    {"name": "Pune Institute of Computer Technology", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Punjab Engineering College", "state": "Punjab", "city": "Chandigarh", "type": "Govt"},
    {"name": "Punjab University", "state": "Punjab", "city": "Patiala", "type": "Govt"},
    {"name": "Punjabi University", "state": "Punjab", "city": "Patiala", "type": "Govt"},
    {"name": "Purnea College of Engineering Purnia", "state": "Bihar", "city": "Purnia", "type": "Govt"},
    {"name": "QIS College of Engineering and Technology", "state": "Andhra Pradesh", "city": "Ongole", "type": "Private"},
    {"name": "R.M.K. College of Engineering and Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "RCC Institute of Information Technology Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "RMD Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "RMD Sinhgad School of Engineering Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "RMK Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "RNS Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "RV College of Engineering", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "RV College of Engineering Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "RVR & JC College of Engineering", "state": "Andhra Pradesh", "city": "Guntur", "type": "Private"},
    {"name": "Raghu Engineering College", "state": "Andhra Pradesh", "city": "Visakhapatnam", "type": "Private"},
    {"name": "Rajagiri School of Engineering Kochi", "state": "Kerala", "city": "Kochi", "type": "Private"},
    {"name": "Rajagiri School of Engineering and Technology", "state": "Kerala", "city": "Kochi", "type": "Private"},
    {"name": "Rajalakshmi Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Rajalakshmi Institute of Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Rajarambapu Institute of Technology Sangli", "state": "Maharashtra", "city": "Sangli", "type": "Private"},
    {"name": "Rajas Engineering College", "state": "Tamil Nadu", "city": "Tirunelveli", "type": "Private"},
    {"name": "Rajasthan Technical University", "state": "Rajasthan", "city": "Kota", "type": "Govt"},
    {"name": "Rajiv Gandhi Institute of Technology Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Rajiv Gandhi Proudyogiki Vishwavidyalaya", "state": "Madhya Pradesh", "city": "Bhopal", "type": "Govt"},
    {"name": "Rajiv Gandhi University", "state": "Arunachal Pradesh", "city": "Itanagar", "type": "Govt"},
    {"name": "Ramachandra College of Engineering", "state": "Andhra Pradesh", "city": "Eluru", "type": "Private"},
    {"name": "Ranchi University", "state": "Jharkhand", "city": "Ranchi", "type": "Govt"},
    {"name": "Rani Durgavati University", "state": "Madhya Pradesh", "city": "Jabalpur", "type": "Govt"},
    {"name": "Rizvi College of Engineering Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Roever Engineering College", "state": "Tamil Nadu", "city": "Perambalur", "type": "Private"},
    {"name": "Royal School of Engineering Guwahati", "state": "Assam", "city": "Guwahati", "type": "Private"},
    {"name": "SASTRA Deemed University", "state": "Tamil Nadu", "city": "Thanjavur", "type": "Deemed"},
    {"name": "SDM College of Engineering and Technology Dharwad", "state": "Karnataka", "city": "Hubli", "type": "Private"},
    {"name": "SJBIT Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "SJCE Mysore", "state": "Karnataka", "city": "Mysore", "type": "Private"},
    {"name": "SNS College of Engineering", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "SNS College of Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "SOA University", "state": "Odisha", "city": "Bhubaneswar", "type": "Deemed"},
    {"name": "SPIT Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "SR Engineering College", "state": "Andhra Pradesh", "city": "Anantapur", "type": "Private"},
    {"name": "SR Engineering College Warangal", "state": "Telangana", "city": "Warangal", "type": "Private"},
    {"name": "SRM Institute of Science and Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Deemed"},
    {"name": "SRM University Sonepat", "state": "Haryana", "city": "Sonipat", "type": "Private"},
    {"name": "SRM Valliammai Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "SSN College of Engineering", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "SV College of Engineering", "state": "Andhra Pradesh", "city": "Kadapa", "type": "Private"},
    {"name": "Sagar University", "state": "Madhya Pradesh", "city": "Sagar", "type": "Govt"},
    {"name": "Sal Institute of Technology Ahmedabad", "state": "Gujarat", "city": "Ahmedabad", "type": "Private"},
    {"name": "Sambalpur University", "state": "Odisha", "city": "Sambalpur", "type": "Govt"},
    {"name": "Sambhram Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Sankalchand Patel College of Engineering Visnagar", "state": "Gujarat", "city": "Visnagar", "type": "Private"},
    {"name": "Sant Longowal Institute of Engineering and Technology", "state": "Punjab", "city": "Sangrur", "type": "Govt"},
    {"name": "Sapthagiri College of Engineering Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Saran College of Engineering Chapra", "state": "Bihar", "city": "Chapra", "type": "Govt"},
    {"name": "Sardar Patel College of Engineering Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Sardar Patel University", "state": "Gujarat", "city": "Anand", "type": "Govt"},
    {"name": "Sardar Vallabhbhai National Institute of Technology", "state": "Gujarat", "city": "Surat", "type": "Govt"},
    {"name": "Sarvajanik College of Engineering Surat", "state": "Gujarat", "city": "Surat", "type": "Private"},
    {"name": "Sasi Institute of Technology and Engineering", "state": "Andhra Pradesh", "city": "Tadepalligudem", "type": "Private"},
    {"name": "Sathyabama Institute of Science and Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Deemed"},
    {"name": "Saurashtra University", "state": "Gujarat", "city": "Rajkot", "type": "Govt"},
    {"name": "Saveetha Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Savitribai Phule Pune University", "state": "Maharashtra", "city": "Pune", "type": "Govt"},
    {"name": "Selvam College of Technology", "state": "Tamil Nadu", "city": "Namakkal", "type": "Private"},
    {"name": "Sengunthar Engineering College", "state": "Tamil Nadu", "city": "Tiruchengode", "type": "Private"},
    {"name": "Sethu Institute of Technology", "state": "Tamil Nadu", "city": "Virudhunagar", "type": "Private"},
    {"name": "Shah and Anchor Kutchhi Engineering College Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Shanmugha Arts Science Technology and Research Academy", "state": "Tamil Nadu", "city": "Thanjavur", "type": "Deemed"},
    {"name": "Sharda University", "state": "Uttar Pradesh", "city": "Noida", "type": "Private"},
    {"name": "Shivaji University", "state": "Maharashtra", "city": "Kolhapur", "type": "Govt"},
    {"name": "Shoolini University", "state": "Himachal Pradesh", "city": "Solan", "type": "Private"},
    {"name": "Shreenivasa Engineering College", "state": "Tamil Nadu", "city": "Dharmapuri", "type": "Private"},
    {"name": "Shri Ramdeobaba College of Engineering Nagpur", "state": "Maharashtra", "city": "Nagpur", "type": "Private"},
    {"name": "Shri Vishnu Engineering College for Women", "state": "Andhra Pradesh", "city": "Bhimavaram", "type": "Private"},
    {"name": "Siddaganga Institute of Technology Tumkur", "state": "Karnataka", "city": "Tumkur", "type": "Private"},
    {"name": "Sido Kanhu Murmu University", "state": "Jharkhand", "city": "Dumka", "type": "Govt"},
    {"name": "Sigma Institute of Engineering Vadodara", "state": "Gujarat", "city": "Vadodara", "type": "Private"},
    {"name": "Sikkim Manipal University", "state": "Sikkim", "city": "Gangtok", "type": "Private"},
    {"name": "Sikkim University", "state": "Sikkim", "city": "Gangtok", "type": "Govt"},
    {"name": "Silicon Institute of Technology Bhubaneswar", "state": "Odisha", "city": "Bhubaneswar", "type": "Private"},
    {"name": "Sinhgad College of Engineering", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Sinhgad Institute of Technology Lonavala", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Sir M. Visvesvaraya Institute of Technology Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Smt. Kashibai Navale College of Engineering Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Sona College of Technology", "state": "Tamil Nadu", "city": "Salem", "type": "Private"},
    {"name": "Sree Sastha Institute of Engineering and Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Sree Vidyanikethan Engineering College", "state": "Andhra Pradesh", "city": "Tirupati", "type": "Private"},
    {"name": "Sreenidhi Institute of Science and Technology Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Sri Balaji Chockalingam Engineering College", "state": "Tamil Nadu", "city": "Arni", "type": "Private"},
    {"name": "Sri Eshwar College of Engineering", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Sri Krishna College of Engineering and Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Sri Krishna College of Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Sri Manakula Vinayagar Engineering College", "state": "Tamil Nadu", "city": "Puducherry", "type": "Private"},
    {"name": "Sri Mittapalli College of Engineering", "state": "Andhra Pradesh", "city": "Guntur", "type": "Private"},
    {"name": "Sri Muthukumaran Institute of Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Sri Ramakrishna Engineering College", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Sri Ramakrishna Institute of Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Sri Sairam College of Engineering", "state": "Tamil Nadu", "city": "Dindigul", "type": "Private"},
    {"name": "Sri Sairam College of Engineering Anekal", "state": "Tamil Nadu", "city": "Bangalore", "type": "Private"},
    {"name": "Sri Sairam Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Sri Sairam Institute of Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Sri Shanmugha College of Engineering and Technology", "state": "Tamil Nadu", "city": "Salem", "type": "Private"},
    {"name": "Sri Vasavi Engineering College", "state": "Andhra Pradesh", "city": "Tadepalligudem", "type": "Private"},
    {"name": "Sri Venkateswara College of Engineering", "state": "Andhra Pradesh", "city": "Tirupati", "type": "Private"},
    {"name": "Sri Venkateswara College of Engineering", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Sri Venkateswara College of Engineering", "state": "Tamil Nadu", "city": "Tirupati", "type": "Private"},
    {"name": "Sri Venkateswara University College of Engineering", "state": "Andhra Pradesh", "city": "Tirupati", "type": "Govt"},
    {"name": "St. Francis Institute of Technology Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "St. Joseph Engineering College Mangalore", "state": "Karnataka", "city": "Mangalore", "type": "Private"},
    {"name": "St. Joseph's College of Engineering", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "St. Joseph's College of Engineering and Technology", "state": "Tamil Nadu", "city": "Thanjavur", "type": "Private"},
    {"name": "St. Martin's Engineering College", "state": "Andhra Pradesh", "city": "Dhulapally", "type": "Private"},
    {"name": "St. Peter's College of Engineering and Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Stanley College of Engineering for Women Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Sun College of Engineering and Technology", "state": "Tamil Nadu", "city": "Nagercoil", "type": "Private"},
    {"name": "Swami Vivekananda Institute of Science and Technology Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Symbiosis Institute of Technology", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "TKM College of Engineering Kollam", "state": "Kerala", "city": "Kollam", "type": "Private"},
    {"name": "TKR College of Engineering Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Tagore Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Tamilnadu College of Engineering", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "Techno India Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Techno India Salt Lake Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Techno India University", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Techno International New Town Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Techno Main Salt Lake Kolkata", "state": "West Bengal", "city": "Kolkata", "type": "Private"},
    {"name": "Terna Engineering College Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Tezpur University", "state": "Assam", "city": "Tezpur", "type": "Govt"},
    {"name": "Thadomal Shahani Engineering College", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Thadomal Shahani Engineering College Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Thapar Institute of Engineering and Technology", "state": "Punjab", "city": "Patiala", "type": "Deemed"},
    {"name": "The NorthCap University", "state": "Haryana", "city": "Gurugram", "type": "Private"},
    {"name": "The Oxford College of Engineering Bangalore", "state": "Karnataka", "city": "Bangalore", "type": "Private"},
    {"name": "Thiagarajar College of Engineering", "state": "Tamil Nadu", "city": "Madurai", "type": "Private"},
    {"name": "Thiruvalluvar College of Engineering and Technology", "state": "Tamil Nadu", "city": "Vandavasi", "type": "Private"},
    {"name": "Toc H Institute of Science Kochi", "state": "Kerala", "city": "Kochi", "type": "Private"},
    {"name": "Trident Academy of Technology Bhubaneswar", "state": "Odisha", "city": "Bhubaneswar", "type": "Private"},
    {"name": "Tripura University", "state": "Tripura", "city": "Agartala", "type": "Govt"},
    {"name": "United College of Engineering Allahabad", "state": "Uttar Pradesh", "city": "Allahabad", "type": "Private"},
    {"name": "United Institute of Technology", "state": "Tamil Nadu", "city": "Coimbatore", "type": "Private"},
    {"name": "University of Delhi", "state": "Delhi", "city": "New Delhi", "type": "Govt"},
    {"name": "University of Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Govt"},
    {"name": "University of Jammu", "state": "Jammu and Kashmir", "city": "Jammu", "type": "Govt"},
    {"name": "University of Kashmir", "state": "Jammu and Kashmir", "city": "Srinagar", "type": "Govt"},
    {"name": "University of Petroleum and Energy Studies", "state": "Uttarakhand", "city": "Dehradun", "type": "Private"},
    {"name": "University of Rajasthan", "state": "Rajasthan", "city": "Jaipur", "type": "Govt"},
    {"name": "Utkal University", "state": "Odisha", "city": "Bhubaneswar", "type": "Govt"},
    {"name": "VIT Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "VNR Vignana Jyothi Institute of Engineering Hyderabad", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "VSB Engineering College", "state": "Tamil Nadu", "city": "Karur", "type": "Private"},
    {"name": "VSSUT Burla", "state": "Odisha", "city": "Sambalpur", "type": "Govt"},
    {"name": "VVIT Guntur", "state": "Andhra Pradesh", "city": "Guntur", "type": "Private"},
    {"name": "Vaagdevi College of Engineering Warangal", "state": "Telangana", "city": "Warangal", "type": "Private"},
    {"name": "Vasavi College of Engineering", "state": "Telangana", "city": "Hyderabad", "type": "Private"},
    {"name": "Veermata Jijabai Technological Institute", "state": "Maharashtra", "city": "Mumbai", "type": "Govt"},
    {"name": "Veermata Jijabai Technological Institute Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Govt"},
    {"name": "Vel Tech High Tech Dr. Rangarajan Dr. Sakunthala Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Velagapudi Ramakrishna Siddhartha Engineering College", "state": "Andhra Pradesh", "city": "Vijayawada", "type": "Private"},
    {"name": "Velammal College of Engineering and Technology", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Velammal College of Engineering and Technology", "state": "Tamil Nadu", "city": "Madurai", "type": "Private"},
    {"name": "Velammal Engineering College", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Vellore Institute of Technology", "state": "Tamil Nadu", "city": "Vellore", "type": "Deemed"},
    {"name": "Veltech Dr. RR & Dr. SR Technical University", "state": "Tamil Nadu", "city": "Chennai", "type": "Private"},
    {"name": "Vidya Academy of Science and Technology Thrissur", "state": "Kerala", "city": "Thrissur", "type": "Private"},
    {"name": "Vidyalankar Institute of Technology Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Vidyasagar University", "state": "West Bengal", "city": "Medinipur", "type": "Govt"},
    {"name": "Vidyavardhini's College of Engineering Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Vignan Institute of Technology and Science", "state": "Andhra Pradesh", "city": "Hyderabad", "type": "Private"},
    {"name": "Vignan University", "state": "Andhra Pradesh", "city": "Guntur", "type": "Private"},
    {"name": "Vijaya Engineering College", "state": "Andhra Pradesh", "city": "Vijayawada", "type": "Private"},
    {"name": "Vikram University", "state": "Madhya Pradesh", "city": "Ujjain", "type": "Govt"},
    {"name": "Vinoba Bhave University", "state": "Jharkhand", "city": "Hazaribagh", "type": "Govt"},
    {"name": "Vishwakarma Institute of Technology Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
    {"name": "Visvesvaraya National Institute of Technology", "state": "Maharashtra", "city": "Nagpur", "type": "Govt"},
    {"name": "Visvesvaraya Technological University", "state": "Karnataka", "city": "Belgaum", "type": "Govt"},
    {"name": "Vivekanand Education Society's Institute of Technology Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Vivekananda Institute of Technology Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "Vivekanandha College of Engineering for Women", "state": "Tamil Nadu", "city": "Namakkal", "type": "Private"},
    {"name": "Walchand College of Engineering", "state": "Maharashtra", "city": "Sangli", "type": "Govt"},
    {"name": "Walchand College of Engineering Sangli", "state": "Maharashtra", "city": "Sangli", "type": "Govt"},
    {"name": "West Bengal University of Technology", "state": "West Bengal", "city": "Kolkata", "type": "Govt"},
    {"name": "Xavier Institute of Engineering Mumbai", "state": "Maharashtra", "city": "Mumbai", "type": "Private"},
    {"name": "YMCA University Faridabad", "state": "Haryana", "city": "Faridabad", "type": "Govt"},
    {"name": "Yeshwantrao Chavan College of Engineering Nagpur", "state": "Maharashtra", "city": "Nagpur", "type": "Govt"},
    {"name": "Zeal College of Engineering and Research Pune", "state": "Maharashtra", "city": "Pune", "type": "Private"},
]

# ==================== HELPER FUNCTIONS ====================

def get_colleges_by_state(state):
    """Return all colleges in a specific state"""
    return [college for college in COLLEGES if college["state"] == state]

def get_colleges_by_city(city):
    """Return all colleges in a specific city"""
    return [college for college in COLLEGES if college["city"] == city]

def get_colleges_by_type(college_type):
    """Return all colleges of a specific type (Govt/Private/Deemed)"""
    return [college for college in COLLEGES if college["type"] == college_type]

def get_college_names():
    """Return list of all college names"""
    return [college["name"] for college in COLLEGES]

def get_college_count_by_state():
    """Return dictionary with state-wise college count"""
    state_count = {}
    for college in COLLEGES:
        state = college["state"]
        state_count[state] = state_count.get(state, 0) + 1
    return state_count

# ==================== DEPARTMENTS ====================
# Engineering Departments List

DEPARTMENTS = [
    # Core / Traditional Engineering
    "Computer Science and Engineering",
    "Information Technology",
    "Electronics and Communication Engineering",
    "Electrical and Electronics Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Biotechnology Engineering",
    "Aerospace Engineering",
    "Automobile Engineering",
    "Industrial Engineering",
    "Production Engineering",
    "Manufacturing Engineering",
    "Metallurgical Engineering",
    "Mining Engineering",
    "Marine Engineering",
    "Naval Architecture",
    "Textile Engineering",
    "Petroleum Engineering",
    "Ceramic Engineering",
    "Agricultural Engineering",
    "Food Technology",
    "Food Processing Engineering",
    "Dairy Technology",
    "Polymer Engineering",
    "Printing Technology",
    "Paper Technology",
    "Rubber Technology",
    "Leather Technology",
    # Computer / IT Specializations
    "Artificial Intelligence and Machine Learning",
    "Artificial Intelligence and Data Science",
    "Computer Engineering",
    "Software Engineering",
    "Computer Science and Design",
    "Computer Science and Business Systems",
    "Computer Science and Information Security",
    "Computer Science and Networking",
    "Computer Science and Engineering with specialization in AI",
    "Computer Science and Engineering with specialization in Data Science",
    "Computer Science and Engineering (Cyber Security)",
    "Computer Science and Engineering (Artificial Intelligence and Machine Learning)",
    "Computer Science and Engineering (Cloud Computing)",
    "Computer Science and Artificial Intelligence",
    "Computer Science and Data Science",
    "Computer Science and Cyber Security",
    "Computer Science and Machine Learning",
    "Computer Science and Cloud Computing",
    "Computer Science and Blockchain Technology",
    "Computer Science and Internet of Things",
    "Computer Science and Game Development",
    "Information Science and Engineering",
    "Information Systems Engineering",
    "Data Engineering",
    "Big Data Engineering",
    "Cloud Engineering",
    "DevOps Engineering",
    "Full Stack Engineering",
    # Electronics / Electrical Specializations
    "Electronics and Instrumentation Engineering",
    "Electronics and Telecommunication Engineering",
    "Electronics Engineering",
    "Instrumentation Engineering",
    "Control and Instrumentation Engineering",
    "Power Engineering",
    "Power Systems Engineering",
    "Electrical Power Engineering",
    "Embedded Systems Engineering",
    "VLSI Design",
    "Microelectronics Engineering",
    "Nanoelectronics Engineering",
    "Communication Systems Engineering",
    "Signal Processing Engineering",
    # Mechanical / Allied Specializations
    "Mechatronics Engineering",
    "Robotics Engineering",
    "Industrial Automation Engineering",
    "Automotive Design Engineering",
    "Thermal Engineering",
    "Energy Engineering",
    "Renewable Energy Engineering",
    "Manufacturing Systems Engineering",
    "Production and Industrial Engineering",
    "Tool Engineering",
    "Materials Engineering",
    "Nanotechnology Engineering",
    "Biomedical Engineering",
    "Biomechanical Engineering",
    # Civil / Infrastructure Specializations
    "Structural Engineering",
    "Construction Engineering",
    "Construction Technology",
    "Environmental Engineering",
    "Geotechnical Engineering",
    "Transportation Engineering",
    "Water Resources Engineering",
    "Urban Engineering",
    "Smart Infrastructure Engineering",
    "Earthquake Engineering",
    "Coastal Engineering",
    "Harbour Engineering",
    "Remote Sensing and GIS",
    "Surveying Engineering",
    # Emerging / Interdisciplinary Engineering
    "Artificial Intelligence Engineering",
    "Machine Learning Engineering",
    "Data Analytics Engineering",
    "Data Science Engineering",
    "Cyber Security Engineering",
    "Internet of Things Engineering",
    "Blockchain Engineering",
    "Quantum Computing Engineering",
    "Augmented Reality Engineering",
    "Virtual Reality Engineering",
    "Game Technology Engineering",
    "Financial Technology Engineering",
    "Healthcare Engineering",
    "Systems Engineering",
    "Engineering Physics",
    "Engineering Mathematics",
    "Engineering Design",
    "Sustainable Engineering"
]

# ==================== DEPARTMENT SHORT NAMES ====================
# Abbreviated department names for compact display

DEPARTMENT_SHORT_NAMES = {
    "Computer Science and Engineering": "CSE",
    "Information Technology": "IT",
    "Electronics and Communication Engineering": "ECE",
    "Electrical and Electronics Engineering": "EEE",
    "Electrical Engineering": "EE",
    "Mechanical Engineering": "ME",
    "Civil Engineering": "CE",
    "Chemical Engineering": "CHE",
    "Biotechnology Engineering": "BT",
    "Aerospace Engineering": "AE",
    "Automobile Engineering": "AUTO",
    "Industrial Engineering": "IE",
    "Production Engineering": "PE",
    "Manufacturing Engineering": "MFG",
    "Metallurgical Engineering": "MET",
    "Mining Engineering": "MIN",
    "Marine Engineering": "MAR",
    "Naval Architecture": "NA",
    "Textile Engineering": "TEX",
    "Petroleum Engineering": "PETRO",
    "Ceramic Engineering": "CER",
    "Agricultural Engineering": "AGR",
    "Food Technology": "FT",
    "Food Processing Engineering": "FPE",
    "Dairy Technology": "DT",
    "Polymer Engineering": "POLY",
    "Printing Technology": "PRINT",
    "Paper Technology": "PAPER",
    "Rubber Technology": "RUB",
    "Leather Technology": "LT",
    "Artificial Intelligence and Machine Learning": "AIML",
    "Artificial Intelligence and Data Science": "AIDS",
    "Computer Engineering": "COMP",
    "Software Engineering": "SE",
    "Computer Science and Design": "CSD",
    "Computer Science and Business Systems": "CSBS",
    "Computer Science and Information Security": "CSIS",
    "Computer Science and Networking": "CSN",
    "Computer Science and Engineering with specialization in AI": "CSE (AI)",
    "Computer Science and Engineering with specialization in Data Science": "CSE (DS)",
    "Computer Science and Engineering (Cyber Security)": "CSE (CS)",
    "Computer Science and Engineering (Artificial Intelligence and Machine Learning)": "CSE (AIML)",
    "Computer Science and Engineering (Cloud Computing)": "CSE (Cloud)",
    "Computer Science and Artificial Intelligence": "CSAI",
    "Computer Science and Data Science": "CSDS",
    "Computer Science and Cyber Security": "CSCS",
    "Computer Science and Machine Learning": "CSML",
    "Computer Science and Cloud Computing": "CSCloud",
    "Computer Science and Blockchain Technology": "CSBlockchain",
    "Computer Science and Internet of Things": "CSIoT",
    "Computer Science and Game Development": "CSGameDev",
    "Information Science and Engineering": "ISE",
    "Information Systems Engineering": "IS",
    "Data Engineering": "DE",
    "Big Data Engineering": "BDE",
    "Cloud Engineering": "Cloud",
    "DevOps Engineering": "DevOps",
    "Full Stack Engineering": "FullStack",
    "Electronics and Instrumentation Engineering": "EI",
    "Electronics and Telecommunication Engineering": "ETC",
    "Electronics Engineering": "EC",
    "Instrumentation Engineering": "INST",
    "Control and Instrumentation Engineering": "CI",
    "Power Engineering": "PWR",
    "Power Systems Engineering": "PS",
    "Electrical Power Engineering": "EP",
    "Embedded Systems Engineering": "ES",
    "VLSI Design": "VLSI",
    "Microelectronics Engineering": "MICRO",
    "Nanoelectronics Engineering": "NANO-E",
    "Communication Systems Engineering": "COMM",
    "Signal Processing Engineering": "SP",
    "Mechatronics Engineering": "MECH",
    "Robotics Engineering": "ROBO",
    "Industrial Automation Engineering": "IA",
    "Automotive Design Engineering": "AUTO-D",
    "Thermal Engineering": "THERM",
    "Energy Engineering": "ENRG",
    "Renewable Energy Engineering": "RE",
    "Manufacturing Systems Engineering": "MSE",
    "Production and Industrial Engineering": "PIE",
    "Tool Engineering": "TOOL",
    "Materials Engineering": "MAT",
    "Nanotechnology Engineering": "NANO",
    "Biomedical Engineering": "BME",
    "Biomechanical Engineering": "BIOME",
    "Structural Engineering": "STRUC",
    "Construction Engineering": "CONST",
    "Construction Technology": "CT",
    "Environmental Engineering": "ENV",
    "Geotechnical Engineering": "GEOTECH",
    "Transportation Engineering": "TRANS",
    "Water Resources Engineering": "WR",
    "Urban Engineering": "URB",
    "Smart Infrastructure Engineering": "SMART-I",
    "Earthquake Engineering": "EQ",
    "Coastal Engineering": "COAST",
    "Harbour Engineering": "HARB",
    "Remote Sensing and GIS": "RSGIS",
    "Surveying Engineering": "SURV",
    "Artificial Intelligence Engineering": "AI",
    "Machine Learning Engineering": "ML",
    "Data Analytics Engineering": "DA",
    "Data Science Engineering": "DS",
    "Cyber Security Engineering": "CyberSec",
    "Internet of Things Engineering": "IoT",
    "Blockchain Engineering": "Blockchain",
    "Quantum Computing Engineering": "QC",
    "Augmented Reality Engineering": "AR",
    "Virtual Reality Engineering": "VR",
    "Game Technology Engineering": "GameTech",
    "Financial Technology Engineering": "FinTech",
    "Healthcare Engineering": "HealthTech",
    "Systems Engineering": "SYS",
    "Engineering Physics": "EP",
    "Engineering Mathematics": "EM",
    "Engineering Design": "ED",
    "Sustainable Engineering": "SUST"
}
