# DEPARTMENTS - Engineering Departments List

DEPARTMENTS = [
    # Core / Traditional Engineering
    "Computer Science and Engineering",
    "Information Technology",
    "Electronics and Communication Engineering",
    "Electrical and Electronics Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Biotechnology Engineering",
    "Aerospace Engineering",
    "Automobile Engineering",
    "Industrial Engineering",
    "Production Engineering",
    "Manufacturing Engineering",
    "Metallurgical Engineering",
    "Mining Engineering",
    "Marine Engineering",
    "Naval Architecture",
    "Textile Engineering",
    "Petroleum Engineering",
    "Ceramic Engineering",
    "Agricultural Engineering",
    "Food Technology",
    "Food Processing Engineering",
    "Dairy Technology",
    "Polymer Engineering",
    "Printing Technology",
    "Paper Technology",
    "Rubber Technology",
    "Leather Technology",
    # Computer / IT Specializations
    "Artificial Intelligence and Machine Learning",
    "Artificial Intelligence and Data Science",
    "Computer Engineering",
    "Software Engineering",
    "Computer Science and Design",
    "Computer Science and Business Systems",
    "Computer Science and Information Security",
    "Computer Science and Networking",
    "Computer Science and Engineering with specialization in AI",
    "Computer Science and Engineering with specialization in Data Science",
    "Computer Science and Engineering (Cyber Security)",
    "Computer Science and Engineering (Artificial Intelligence and Machine Learning)",
    "Computer Science and Engineering (Cloud Computing)",
    "Computer Science and Artificial Intelligence",
    "Computer Science and Data Science",
    "Computer Science and Cyber Security",
    "Computer Science and Machine Learning",
    "Computer Science and Cloud Computing",
    "Computer Science and Blockchain Technology",
    "Computer Science and Internet of Things",
    "Computer Science and Game Development",
    "Information Science and Engineering",
    "Information Systems Engineering",
    "Data Engineering",
    "Big Data Engineering",
    "Cloud Engineering",
    "DevOps Engineering",
    "Full Stack Engineering",
    # Electronics / Electrical Specializations
    "Electronics and Instrumentation Engineering",
    "Electronics and Telecommunication Engineering",
    "Electronics Engineering",
    "Instrumentation Engineering",
    "Control and Instrumentation Engineering",
    "Power Engineering",
    "Power Systems Engineering",
    "Electrical Power Engineering",
    "Embedded Systems Engineering",
    "VLSI Design",
    "Microelectronics Engineering",
    "Nanoelectronics Engineering",
    "Communication Systems Engineering",
    "Signal Processing Engineering",
    # Mechanical / Allied Specializations
    "Mechatronics Engineering",
    "Robotics Engineering",
    "Industrial Automation Engineering",
    "Automotive Design Engineering",
    "Thermal Engineering",
    "Energy Engineering",
    "Renewable Energy Engineering",
    "Manufacturing Systems Engineering",
    "Production and Industrial Engineering",
    "Tool Engineering",
    "Materials Engineering",
    "Nanotechnology Engineering",
    "Biomedical Engineering",
    "Biomechanical Engineering",
    # Civil / Infrastructure Specializations
    "Structural Engineering",
    "Construction Engineering",
    "Construction Technology",
    "Environmental Engineering",
    "Geotechnical Engineering",
    "Transportation Engineering",
    "Water Resources Engineering",
    "Urban Engineering",
    "Smart Infrastructure Engineering",
    "Earthquake Engineering",
    "Coastal Engineering",
    "Harbour Engineering",
    "Remote Sensing and GIS",
    "Surveying Engineering",
    # Emerging / Interdisciplinary Engineering
    "Artificial Intelligence Engineering",
    "Machine Learning Engineering",
    "Data Analytics Engineering",
    "Data Science Engineering",
    "Cyber Security Engineering",
    "Internet of Things Engineering",
    "Blockchain Engineering",
    "Quantum Computing Engineering",
    "Augmented Reality Engineering",
    "Virtual Reality Engineering",
    "Game Technology Engineering",
    "Financial Technology Engineering",
    "Healthcare Engineering",
    "Systems Engineering",
    "Engineering Physics",
    "Engineering Mathematics",
    "Engineering Design",
    "Sustainable Engineering"
]

# DEPARTMENT_SHORT_NAMES - Shortened department names for display
DEPARTMENT_SHORT_NAMES = {
    "Computer Science and Engineering": "CSE",
    "Information Technology": "IT",
    "Electronics and Communication Engineering": "ECE",
    "Electrical and Electronics Engineering": "EEE",
    "Electrical Engineering": "EE",
    "Mechanical Engineering": "ME",
    "Civil Engineering": "CE",
    "Chemical Engineering": "CHE",
    "Biotechnology Engineering": "BT",
    "Aerospace Engineering": "AE",
    "Automobile Engineering": "AUTO",
    "Industrial Engineering": "IE",
    "Production Engineering": "PE",
    "Manufacturing Engineering": "MFG",
    "Metallurgical Engineering": "MET",
    "Mining Engineering": "MIN",
    "Marine Engineering": "MAR",
    "Naval Architecture": "NA",
    "Textile Engineering": "TEX",
    "Petroleum Engineering": "PETRO",
    "Ceramic Engineering": "CER",
    "Agricultural Engineering": "AGR",
    "Food Technology": "FT",
    "Food Processing Engineering": "FPE",
    "Dairy Technology": "DT",
    "Polymer Engineering": "POLY",
    "Printing Technology": "PRINT",
    "Paper Technology": "PAPER",
    "Rubber Technology": "RUB",
    "Leather Technology": "LT",
    "Artificial Intelligence and Machine Learning": "AIML",
    "Artificial Intelligence and Data Science": "AIDS",
    "Computer Engineering": "COMP",
    "Software Engineering": "SE",
    "Computer Science and Design": "CSD",
    "Computer Science and Business Systems": "CSBS",
    "Computer Science and Information Security": "CSIS",
    "Computer Science and Networking": "CSN",
    "Computer Science and Engineering with specialization in AI": "CSE (AI)",
    "Computer Science and Engineering with specialization in Data Science": "CSE (DS)",
    "Computer Science and Engineering (Cyber Security)": "CSE (CS)",
    "Computer Science and Engineering (Artificial Intelligence and Machine Learning)": "CSE (AIML)",
    "Computer Science and Engineering (Cloud Computing)": "CSE (Cloud)",
    "Computer Science and Artificial Intelligence": "CSAI",
    "Computer Science and Data Science": "CSDS",
    "Computer Science and Cyber Security": "CSCS",
    "Computer Science and Machine Learning": "CSML",
    "Computer Science and Cloud Computing": "CSCloud",
    "Computer Science and Blockchain Technology": "CSBlockchain",
    "Computer Science and Internet of Things": "CSIoT",
    "Computer Science and Game Development": "CSGameDev",
    "Information Science and Engineering": "ISE",
    "Information Systems Engineering": "IS",
    "Data Engineering": "DE",
    "Big Data Engineering": "BDE",
    "Cloud Engineering": "Cloud",
    "DevOps Engineering": "DevOps",
    "Full Stack Engineering": "FullStack",
    "Electronics and Instrumentation Engineering": "EI",
    "Electronics and Telecommunication Engineering": "ETC",
    "Electronics Engineering": "EC",
    "Instrumentation Engineering": "INST",
    "Control and Instrumentation Engineering": "CI",
    "Power Engineering": "PWR",
    "Power Systems Engineering": "PS",
    "Electrical Power Engineering": "EP",
    "Embedded Systems Engineering": "ES",
    "VLSI Design": "VLSI",
    "Microelectronics Engineering": "MICRO",
    "Nanoelectronics Engineering": "NANO-E",
    "Communication Systems Engineering": "COMM",
    "Signal Processing Engineering": "SP",
    "Mechatronics Engineering": "MECH",
    "Robotics Engineering": "ROBO",
    "Industrial Automation Engineering": "IA",
    "Automotive Design Engineering": "AUTO-D",
    "Thermal Engineering": "THERM",
    "Energy Engineering": "ENRG",
    "Renewable Energy Engineering": "RE",
    "Manufacturing Systems Engineering": "MSE",
    "Production and Industrial Engineering": "PIE",
    "Tool Engineering": "TOOL",
    "Materials Engineering": "MAT",
    "Nanotechnology Engineering": "NANO",
    "Biomedical Engineering": "BME",
    "Biomechanical Engineering": "BIOME",
    "Structural Engineering": "STRUC",
    "Construction Engineering": "CONST",
    "Construction Technology": "CT",
    "Environmental Engineering": "ENV",
    "Geotechnical Engineering": "GEOTECH",
    "Transportation Engineering": "TRANS",
    "Water Resources Engineering": "WR",
    "Urban Engineering": "URB",
    "Smart Infrastructure Engineering": "SMART-I",
    "Earthquake Engineering": "EQ",
    "Coastal Engineering": "COAST",
    "Harbour Engineering": "HARB",
    "Remote Sensing and GIS": "RSGIS",
    "Surveying Engineering": "SURV",
    "Artificial Intelligence Engineering": "AI",
    "Machine Learning Engineering": "ML",
    "Data Analytics Engineering": "DA",
    "Data Science Engineering": "DS",
    "Cyber Security Engineering": "CyberSec",
    "Internet of Things Engineering": "IoT",
    "Blockchain Engineering": "Blockchain",
    "Quantum Computing Engineering": "QC",
    "Augmented Reality Engineering": "AR",
    "Virtual Reality Engineering": "VR",
    "Game Technology Engineering": "GameTech",
    "Financial Technology Engineering": "FinTech",
    "Healthcare Engineering": "HealthTech",
    "Systems Engineering": "SYS",
    "Engineering Physics": "EP",
    "Engineering Mathematics": "EM",
    "Engineering Design": "ED",
    "Sustainable Engineering": "SUST"
}
